### ISSUE TITLE
PROPOSAL - Use bot account instead of normal user

### ISSUE THREAD

**Issue by hanzei** [standup-raven/standup-raven#10]
**Is your feature request related to a problem? Please describe.**
Currently admins have to create a user account for this plugin to work. They also have to enable two setting. See https://github.com/standup-raven/standup-raven/blob/master/docs/installation.md#mattermost-configuration. Both put additional work on the admin.

**Describe the solution you'd like**
This can be reduced by the plugin automatically creating a `Raven` bot account and using this one to post the messages.

**Describe alternatives you've considered**
Make the bot username configurable.

**Comment by harshilsharma** [comment]
@hanzei thanks for the suggestion!

Agreed, it will minimize two steps from setup.
