### ISSUE TITLE
BUG - Command with a trigger of 'standup' not found

### ISSUE THREAD

**Issue by ndtunitydev** [standup-raven/standup-raven#106]
**Summary**
Can't use the command `/standup config`.

**Steps To Reproduce**
1. Upload the plugin binary for your platform in Mattermost System Console > Plugins (BETA) > Management.
2. Get into the channel and try using the command `/standup config`
3. A Message `Command with a trigger of 'standup' not found. To send a message beginning with "/", try adding an empty space at the beginning of the message.` appeared.

**Expected behavior**
The setting menu should appear.

**Observed Behavior**
A Message `Command with a trigger of 'standup' not found. To send a message beginning with "/", try adding an empty space at the beginning of the message.` appeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/50861120/64588540-e036fd00-d3cc-11e9-8dc8-4e4f8a41a198.png)

**Environment**
-  Mattermost version: 4.20 (Open Source Team Edition)
-  Platform: Windows

**Comment by harshilsharma63** [comment]
Hi @ndtunitydev can you make sure the plugin was enabled?

**Comment by ndtnarudol** [comment]
@harshilsharma63 

Yes, the plugin was enabled.

![画像の貼り付け先- 2019-10-1 18-32](https://user-images.githubusercontent.com/48474751/65952161-a907b900-e46b-11e9-8fea-b4d75b829e96.png)
![画像の貼り付け先- 2019-10-1 18-33](https://user-images.githubusercontent.com/48474751/65951051-7492fd80-e469-11e9-9ae4-a1320dbf5d0b.png)

**Comment by jatinjtg** [comment]
@ndtnarudol you have to configure standup for a channel.To configure the standup for a channel use command - /standup config.To know about all the available slash commands you can use- /standup help

**Comment by ndtnarudol** [comment]
> @ndtnarudol you have to configure standup for a channel.To configure the standup for a channel use command - /standup config.To know about all the available slash commands you can use- /standup help

@jatinjtg 
Thanks for the response but as being said in the [report](https://github.com/standup-raven/standup-raven/issues/106#issue-491472317), I can't use the command `/standup config`.

**Comment by ndtnarudol** [comment]
> @ndtnarudol you have to configure standup for a channel.To configure the standup for a channel use command - /standup config.To know about all the available slash commands you can use- /standup help

@jatinjtg 
Thanks for the response but as being said in the [report](https://github.com/standup-raven/standup-raven/issues/106#issue-491472317), I can't use the command `/standup config`.

**Comment by jatinjtg** [comment]
@ndtnarudol The minimum mattermost version needed for standup raven is 5.12.0.

**Comment by ndtnarudol** [comment]
@jatinjtg 
ah... I see.
The version of my mattermost is 4.20.

Thanks for the information!

**Comment by Ziv00s3** [comment]
> @ndtnarudol The minimum mattermost version needed for standup raven is 5.12.0.

I have the same problem on 5.21.

**Comment by harshilsharma63** [comment]
@Ziv00s3 @ndtunitydev can you check Mattermost logs for some error in the plugin?

**Comment by Ziv00s3** [comment]
@harshilsharma63 fixed, I have uploaded Darwin version on Linux. Thank you!

**Comment by harshilsharma63** [comment]
I'm closing this one now as you were able to resolve the issue. Feel free to reopen if needed.
