### ISSUE TITLE
PROPOSAL - Add custom frequency for the stand up prompts (DAILY, WEEKLY, etc.)

### ISSUE THREAD

**Issue by attzonko** [standup-raven/standup-raven#107]
**Is your feature request related to a problem? Please describe.**
We have a channel that would like to use Standup Raven on a weekly based time frame, instead of daily.

**Describe the solution you'd like**
It would be very helpful to be able to have stand up raven query a channel weekly instead of daily.

**Describe alternatives you've considered**
Don't know of any alternatives.

**Additional context**

**Comment by harshilsharma63** [comment]
@attzonko that's a really nice idea! We'll work on it, or maybe you want to help on this one?

**Comment by harshilsharma63** [comment]
@attzonko this is being done as part of #128. Please check out the WIP screenshots in there and feel free to make any suggestions.

Closing this one.

**Comment by attzonko** [comment]
> @attzonko this is being done as part of #128. Please check out the WIP screenshots in there and feel free to make any suggestions.
> 
> Closing this one.

Looks good 👍
