### ISSUE TITLE
BUG - user profile image missing

### ISSUE THREAD

**Issue by tgly307** [standup-raven/standup-raven#12]
**Summary**
user profile image missing in channel.
![image](https://user-images.githubusercontent.com/25153311/56902585-2e59fc80-6acd-11e9-9600-bd48fb28a4a8.png)
(my bot name is github)

**Steps To Reproduce**
1. install plugin
2. set plugin config ( bot name, time zone)
3. use /standupconfig and /standupaddmembers to activate plugin and add myself to group
4. When plugin send this message, profile image is missing (got 403 forbidden error).

**Expected behavior**
What you expected to happen.

**Observed Behavior**
What actually happened.

**Screenshots**

**Environment (if applicable):**
-  OS: windows and andriod
-  Browser: chrome
-  Version 73

I found the url of profile image is `https://mysite.com/api/v4/image?url=%2Fplugins%2Fstandup-raven%2Fstatic%2Flogo.png`, it doesn't work. And I tried the url   `https://mysite.com/api/v4/image?url=https%3A%2F%2Fmysite.com%2Fplugins%2Fstandup-raven%2Fstatic%2Flogo.png`, it works. 
So I guess maybe this is a bug of missing something in icon config.

**Comment by harshilsharma** [comment]
@tgly307 thank you for reporting the bug!

Which Mattermost version are you using?

Also, can you try with `Image Proxy` disabled if it's enabled? You can find the settings under `System Console` > `Files` > `Storage` > `Enable Image Proxy`.

**Comment by tgly307** [comment]
Oh, thanks a lot! My image proxy is enabled, I turn it down and it works. I will close this.
