### ISSUE TITLE
QUESTION: Missing Standup Raven Icon

### ISSUE THREAD

**Issue by attzonko** [standup-raven/standup-raven#120]
Hi,

We are seeing that once in a while the standup-raven icon disappears from the UI. As the admin, I have tried re-installing the plugin, restarting mattermost, but I can't seem to find a way to make it work. Do you have some way of re-adding the icon to the UI?

**Comment by attzonko** [comment]
Got a bit more data. If I install version 1.5 the icon comes back. As soon as I install 2.0 the icon disappears again. This process is very repeatable in the current state of the system.

**Comment by harshilsharma63** [comment]
@attzonko thanks for the bug report! What version of Mattermost are you on?

**Comment by attzonko** [comment]
5.14.3

**Comment by harshilsharma63** [comment]
@attzonko Okay. I'll try it on my end.

**Comment by mthld** [comment]
Reproduce this on Mattermost 5.15. Interesting point: on the iOS app I can still see it.

**Comment by harshilsharma63** [comment]
@attzonko @mthld I tried on 5.14.3 and 5.15.3 and it's working perfectly for me. Would you mind trying out the latest v2.1.0 release?

**Comment by mthld** [comment]
Hi @harshilsharma63 

> Would you mind trying out the latest v2.1.0 release?

Fixed. Thanks!

**Comment by harshilsharma63** [comment]
@mthld awesome!

@attzonko can you also give it a try?

**Comment by attzonko** [comment]
I installed v2.1.0 and the icon came back. Will let you know if the issue comes back once this version has been in use for a while.

**Comment by harshilsharma63** [comment]
@attzonko thanks for confirming!
