### ISSUE TITLE
BUG - Multiple notifications send on reminder

### ISSUE THREAD

**Issue by jprusch** [standup-raven/standup-raven#121]
**Summary**
We get multiple reminder notifications instead of one

**Steps To Reproduce**
1. Created a standup with window open & window close reminders
2. Added standup members

**Expected behavior**
Receive ONE reminder notice 

**Observed Behavior**
We received three reminder notices
**Screenshots**
![image](https://user-images.githubusercontent.com/9337414/68469564-b65a5500-021a-11ea-8830-afff77a87b6d.png)

**Environment**
-  Mattermost version: 5.16.2
-  OS: Linux Debian
-  Platform: All clients
-  Browser (if applicable): All browsers

**Comment by harshilsharma63** [comment]
Hi @jprusch . Are you by any chance running Mattermost in high-availability mode?

**Comment by jprusch** [comment]
Never mind. Must have been a sort of glitch. Didn't happen twice.
