### ISSUE TITLE
BUG - config command failed v2.1 

### ISSUE THREAD

**Issue by DeathNeeeet** [standup-raven/standup-raven#126]
**Summary**
`/standup config` command failed v2.1 (Mattermost  5.14.2)

**Steps To Reproduce**
1. type `/standup config`
2. fill inputs
3. Save click
4. See errors (500 Internal Server Error)

v2.0 works well.

**Environment**
-  Mattermost version: 5.14.2
-  OS: every OS
-  Platform: browser, desktop app, mobile browser, mobile app
-  Browser (if applicable): every browser

**Comment by memlucky71** [comment]
I also had this problem with version 2.1, so I had to use version 2.0.

**Comment by harshilsharma63** [comment]
@DeathNeeeet @memlucky71 thank you for reporting the bug. I'm on it!

**Comment by harshilsharma63** [comment]
@DeathNeeeet @memlucky71 please try out https://github.com/standup-raven/standup-raven/releases/tag/v2.2.0 and let me know if the bug is resolved for you.
