### ISSUE TITLE
PROPOSAL - WEEKLY STANDUP SUPPORT

### ISSUE THREAD

**Issue by Moyni84** [standup-raven/standup-raven#128]
I would like to be able to use Raven for a weekly standup.

This could be done by exposing "Work Week Start" and "Work Week End" to the standup config.

**Comment by harshilsharma63** [comment]
@Moyni84 thanks for the feature suggestion!

We've received similar requests for other users as well. In a more generic way, we can allow users to define their custom standup frequency - daily, every 2 days or simply every x days. We'd definitely consider this feature request and work on it as soon as I'm able to get some bandwidth.

Wondering if you'd be interested in working on this?

**Comment by Moyni84** [comment]
Thanks for getting back to me. This would be great. My Java/JavaScript is non existent unfortunately otherwise I would jump right in (goal for 2020).


Cheers, Michael


---- Harshil Sharma wrote ----


@Moyni84<https://github.com/Moyni84> thanks for the feature suggestion!

We've received similar requests for other users as well. In a more generic way, we can allow users to define their custom standup frequency - daily, every 2 days or simply every x days. We'd definitely consider this feature request and work on it as soon as I'm able to get some bandwidth.

Wondering if you'd be interested in working on this?

**Comment by bobchao** [comment]
If you only have one group of people need to do the stand-up report (or all the groups on your server do the report on exactly the same day of the week,) then:

1. Set both workWeekStart and workWeekEnd on the day you want, say Saturday.
2. Add a ```if``` block to handle the situation when workWeekStart == workWeekEnd

it might help... I just tried this approach myself to see if everything goes well.

**Comment by bobchao** [comment]
FYI the method I mentioned in the last comment works pretty well. However, the whole instance will follow the same rule, which might not be helpful in some cases.

**Comment by Moyni84** [comment]
Thanks @bobchao but for my usage I would like to configure per channel. Given the explosion of WFH at the moment, I shall see if I can find someone to make this change.

**Comment by helperkeys** [comment]
I also have the requirement of configuration per channel. Once I'm off hotel wifi, I'll be looking to submit a PR for this.

**Comment by harshilsharma63** [comment]
@Moyni84 @bobchao @helperkeys this is definitely on my list. I understand the urgent need during the WFH situation and am trying to get as much done on Standup Raven as possible.

@Moyni84 just to clarify, do you want to submit standup one a week or do you want an aggregated weekly report? Same question for @helperkeys and @bobchao .

Thanks!

**Comment by bobchao** [comment]
I would like to have one report per week since we are a volunteer group, once a week will be better than report everyday.

**Comment by harshilsharma63** [comment]
@bobchao and you want to fill standups also once a week?

**Comment by bobchao** [comment]
@harshilsharma63 yes

**Comment by Moyni84** [comment]
Same here. Making how many days selectable per channel would be the ideal but my use case is once a week. Saw this and thought it could be used on the front end. https://github.com/ntdb/react-weekday-picker.

**Comment by negbie** [comment]
+1 for filling standups once a week!

**Comment by helperkeys** [comment]
It doesn't have to necessarily be once per week. I would like the ability to specify the frequency in which we submit standup _per_ channel. 

Aggregated weekly reports would be great as well!

**Comment by helperkeys** [comment]
> @Moyni84 @bobchao @helperkeys this is definitely on my list. I understand the urgent need during the WFH situation and am trying to get as much done on Standup Raven as possible.
> 
> @Moyni84 just to clarify, do you want to submit standup one a week or do you want an aggregated weekly report? Same question for @helperkeys and @bobchao .
> 
> Thanks!

It doesn't have to necessarily be once per week. I would like the ability to specify the frequency in which we submit standup per channel.

Aggregated weekly reports would be great as well!

**Comment by harshilsharma63** [comment]
@helperkeys yes, that's definitely a more generic approach. I'm trying to replicate something like a recurring event in a calender.

**Comment by harshilsharma63** [comment]
A screenshot of progress so far. Would love to get some comments and feedback on this -

![localhost_8065_team-a_channels_standup-raven (2)](https://user-images.githubusercontent.com/8211068/81499408-15dc0f00-92e9-11ea-9d46-001e750c59c5.png)

**Comment by bobchao** [comment]
Looks good to me 👯

**Comment by urba1n** [comment]
Good as well. Do you plan to link the standup filled outside the Window Time to the next Window Time available ? E.g. for a weekly standup every Monday between 07:00-09:30, if collaborators are filling it on previous Friday due to a leave of absence on Monday, they should be linked to the Monday standup.

**Comment by Moyni84** [comment]
Covers everything I was looking for. Thanks.

**Comment by harshilsharma63** [comment]
@urba1n I'll add a date picker to standup form to allow submitting standups for any arbitrary date. This covers many more cases than just future standup. Some users like to keep a record of standups and want to fill past standups in case someone missed it.

**Comment by harshilsharma63** [comment]
@Moyni84 Glad it works for you! The UI is going to be much more refined though.

**Comment by harshilsharma** [comment]
@Moyni84 @bobchao @helperkeys @negbie @urba1n Apologies for not updating here.

I'm super excited to announce that this feature is now done and ready 🎉🎉🎉. Not only have we introduced weekly configurable standups but also monthly standups - on first weekday, last Monday, etc.

The feature is part of v3 release so please try it out and as usual, let us know any feedback you have.

Consider subscribing at https://www.standupraven.com/ to receive additional product updates and release notifications.

Thanks!

**Comment by harshilsharma63** [comment]
@Moyni84 @bobchao @helperkeys @negbie @urba1n Apologies for not updating here.

I'm super excited to announce that this feature is now done and ready 🎉🎉🎉. Not only have we introduced weekly configurable standups but also monthly standups - on first weekday, last Monday, etc.

The feature is part of v3 release so please try it out and as usual, let us know any feedback you have.

Consider subscribing at https://www.standupraven.com/ to receive additional product updates and release notifications.

Thanks!

**Comment by Moyni84** [comment]
Thank you so much. I spotted this yesterday and have put in a request to upgrade to this version. I shall let you know how it goes.
