### ISSUE TITLE
BUG - mattermost crash when modify sections after user add tasks

### ISSUE THREAD

**Issue by tgly307** [standup-raven/standup-raven#13]
**Summary**
when user modify the sections use /standupconfig after someone add tasks, the mattermost will crash when click raven button on channel top.

**Steps To Reproduce**
1. install plugin and set the config use /standupconfig ,for example set sections "yesterday" and "today"
2. add member use /standupaddmembers , for example add userA to group
3. userA add tasks by click raven button on channel top
4. modify sections use /standupconfig, for example delete "yestoday"
5. userA click the button and mattermost crash, must reload the view.

**Expected behavior**
I think maybe it should clear all tasks set before and let user add task again.

**Observed Behavior**
mattermost crash

**Screenshots**

**Environment (if applicable):**
-  OS: windows10 desktop app 4.2.0

**Comment by harshilsharma** [comment]
@tgly307 huge thanks for reporting the bug!

Wondering if you'd be open to help with a fix for it?

**Comment by tgly307** [comment]
I am very happy to help, but I am very strange to golang and have never done related development.

**Comment by harshilsharma** [comment]
@tgly307 ah, no issue there! We'll look into it.

**Comment by Routhinator** [comment]
This happens in the client and Firefox (for linux). 

Relevant JS console output from Firefox:

![Screenshot from 2019-05-07 15-01-00](https://user-images.githubusercontent.com/727535/57336119-b8135680-70d9-11e9-965b-b80d1c595b33.png)

**Comment by Routhinator** [comment]
This may have a trigger: someone edited the questions after standups were submitted by the affected users. Not all users are seeing the issue.

**Comment by harshilsharma** [comment]
@Routhinator you're correct! It happens when one of the section from current standup config doesn't exist n your standup, probably when someone changes the config. Will be pushing a fix soon.

**Comment by harshilsharma** [comment]
This issue is fixed in #17 and will be available in the next release.
