### ISSUE TITLE
BUG - Incorrect request path when mattermost runs in a subdir

### ISSUE THREAD

**Issue by sphr** [standup-raven/standup-raven#130]
**Summary**
The plugin does not account for mattermost running in a subdir https://example.com/chat/ and gives a error 404 since it's hardlinked to /plugin/

**Steps To Reproduce**
Set up mattermost with a URL that includes a subdir. Load the plugin. start it with /standup configure and try to enable or disable it in a channel and it will now throw a 404 in the standup window.
 
**Expected behavior**
Plugin should perform actions by using mattermost config variable SiteURL as it's base.

**Observed Behavior**
Wrong URL is requested by the plugin.

**Environment**
- Is not dependent on any client browser configuration.

**Workaround**
I have managed to modify standup-raven/webapp/main.js and modified this line to include my chat subdir:
var PLUGIN_BASE_URL = _utils2.default.getBaseURL() + '/plugins/' + PLUGIN_NAME;

New line is now:
var PLUGIN_BASE_URL = _utils2.default.getBaseURL() + '/chat/plugins/' + PLUGIN_NAME;

**Comment by harshilsharma63** [comment]
@sphr thanks for the bug report! 

That makes sense. Can you confirm that in your setup you would have `https://example.com/chat` set as `Site URL`? If so, we can use that as the base URL.

**Comment by sphr** [comment]
That is correct, https://example.com/chat is mattermost's siteurl

**Comment by harshilsharma63** [comment]
@sphr yes, of course it can be different. As long as site URL is what Matterost runs on, we can use that.

Would you by any chance be interested in implementing this?

**Comment by sphr** [comment]
I'm not confident enough in javascript and how the variables propagate between mattermost and the addon to suggest a solution formulated in code at this time.

**Comment by harshilsharma63** [comment]
@sphr no problem! I'll pick this as the next item on my plate.

**Comment by sphr** [comment]
This actually seems to impact other plugins as well, I have issued a bug report with mattermost as well.
https://github.com/mattermost/mattermost-server/issues/14106

**Comment by harshilsharma63** [comment]
@sphr Yes, all plugins developers will have to take care of this. I think there's little Mattermost can do about this. They can definitely mention this in the plugin development guide.

**Comment by harshilsharma63** [comment]
For an update on this issue, I've made the code changes and I'm testing it now. It should be good to release this week.

**Comment by harshilsharma63** [comment]
@sphr This has been implemented as part of [v2.4.0](https://github.com/standup-raven/standup-raven/releases/tag/v2.4.0) release. Please update your plugin instalation.
