### ISSUE TITLE
PROPOSAL - App/Mobile Support

### ISSUE THREAD

**Issue by Grienauer** [standup-raven/standup-raven#133]
**Is your feature request related to a problem? Please describe.**
Currently submitting a Standup by a user is not supported in the mobile app (there is no button or slash command to start a submission.

**Describe the solution you'd like**
Add a / command like /standup write and a bot is asking you the questions one by one and you can separate them via ";" per Question…
could be related to https://github.com/standup-raven/standup-raven/issues/9#issuecomment-491524921

**Describe alternatives you've considered**
maybe there is also a native solution for it, so it will be displayed by the Mattermost mobile client?

Thank You for this tool!

**Comment by harshilsharma63** [comment]
Hi @Grienauer , thanks for the suggestion!

Mattermost mobile app currently doesn't support webapp plugins so we cannot display any Standup Raven button or open up a modal on mobile. Slash commands work fine though.

The idea of using slash commands in an interactive way to submit standups sounds cool! We'll consider this in our next iteration.

**Comment by harshilsharma63** [comment]
@Grienauer We wish to include more functionalities to the standup modal in the future. Using slash commands might not allow the same user experience as a modal would.

We recommend you use Mattermost on a mobile browser for submitting standups as it's fully supported over there.
