### ISSUE TITLE
BUG - User Icon too big in Standup Report

### ISSUE THREAD

**Issue by MatthiasDamm** [standup-raven/standup-raven#134]
**Summary**
The profile of the user image in standup report is too big

**Steps To Reproduce**
1. Upload image to your user profile account (tested png, jpeg with different sizes)
2. Create standup config in a room
3. Suuply the standup for your user

**Expected behavior**
Icon should be max height of username like in docs

**Observed Behavior**
see error

**Screenshots**
![image](https://user-images.githubusercontent.com/9323393/74820201-e75e2180-5301-11ea-96f0-7a0c8256f213.png)

**Environment**
-  Mattermost version: e.g. 5.18
-  OS: Linux
-  Platform: desktop app, desktop browser
-  Browser (if applicable): chrome
-  Platform Version: e.g. 75

**Comment by harshilsharma63** [comment]
@MatthiasDamm thanks for reporting the bug.

This was, however, a bug with Mattermost itself (see [here](https://github.com/mattermost/mattermost-server/issues/13539)) and it has been resolved in Mattermosr v5.19. I suggest you upgrade to Mattermost v5.19 or above.
