### ISSUE TITLE
BUG - Releases labeled incorrectly

### ISSUE THREAD

**Issue by svelle** [standup-raven/standup-raven#138]
**Summary**
The linux release includes a plugin.exe

**Steps To Reproduce**
1. Download https://github.com/standup-raven/standup-raven/releases/download/v2.2.0/mattermost-plugin-standup-raven-v2.2.0-linux-amd64.tar.gz
2. Extract and check server folder

**Comment by svelle** [comment]
looks like they're all labeled plugin.exe.. not the best idea. Now I've got to look into why the plugin won't start :sweat_smile:

**Comment by harshilsharma63** [comment]
@svelle yes, the executable binary in all of them is named `plugin.exe`. Just curious, were you able to get t working?
