### ISSUE TITLE
PROPOSAL - Add option to order stand-ups alphabetically

### ISSUE THREAD

**Issue by ptr0x1** [standup-raven/standup-raven#139]
**Is your feature request related to a problem? Please describe.**
We are testing out daily standups with more than 30 people. The user aggregated view is good but it is hard to scan through and find the exact person we're looking for.

**Describe the solution you'd like**
It would be great to order based on "username" or "First Name Last Name" when showing the results.

**Describe alternatives you've considered**
Searching for a specific person's name is a good alternative if I'm looking for an exact person but, if the feature is not a huge development, this would help more. Additionally I also saw another feature request around setting up different groups. That would also work as we could group our people up - they fill one standup but we can look at the group results separately.

I haven't developed in GO yet but would be happy to help out with either approach if you can provide some documentation/starting help.

**Comment by harshilsharma63** [comment]
@ptr0x1 that's a really useful feature and pretty easy to implement. I'll pick this one ASAP. If you're interested, feel free to contribute on this.

**Comment by harshilsharma63** [comment]
@ThiefMaster this has been implemented in the latest release - 2.3.0. Please update your plugin installation.
