### ISSUE TITLE
PROPOSAL - Hide channel header button if standups are not enabled

### ISSUE THREAD

**Issue by ThiefMaster** [standup-raven/standup-raven#140]
I don't want the raven button to show up at all unless standups are configured in a channel.

Rationale: A few users asked me to enable this plugin on our somewhat large instance, so I don't want to have this button show up if the plugin isn't used in 99% of the channels at all.

**Comment by harshilsharma63** [comment]
@ThiefMaster thanks for the feature suggestion. That does make sense.

I'm gonna try this out but feel free to contribute on this (or any other issue) meanwhile.

**Comment by harshilsharma63** [comment]
@ThiefMaster This feature has been requested by a few more people as well.  Although the channel header button cannot be conditionally enabled or disabled, there is an alternate solution to this.

We can add a plugin configuration to entirely disable the channel header button from all channels. Users can access standup dialog via the `/staandup` slash command and continue as usual.

How does that sound?

**Comment by ThiefMaster** [comment]
Sounds like a good tradeoff. But allowing conditionally-shown header buttons would be a good feature for a future Mattermost version.

**Comment by harshilsharma63** [comment]
@ThiefMaster agreed. This is something Mattermost doesn't provide but I've already created a ticket over there regarding this.

**Comment by harshilsharma63** [comment]
@ThiefMaster I was able to do it as expected - the channel header button hides in channels where standup is not configured. This will be released in the upcoming release next week. 

In case you want to deploy it right away, you may build the plugin by self or just let me know and I can give you compiled binaries for this.

**Comment by harshilsharma63** [comment]
@ThiefMaster this has been released as part of [v2.5.0](https://github.com/standup-raven/standup-raven/releases/tag/v2.5.0). Please upgrade your plugin installation.

**Comment by bbodenmiller** [comment]
@harshilsharma63 looks like this works... 
![image](https://user-images.githubusercontent.com/1192780/80265988-795e0f80-864e-11ea-8867-9ad4d33b1cf6.png)

... unless you have a second plugin configured that adds a channel header icon...
![image](https://user-images.githubusercontent.com/1192780/80266011-9eeb1900-864e-11ea-9728-1f8fc1f7c7c9.png)

**Comment by harshilsharma63** [comment]
@bbodenmiller ah! Thanks for catching this. I'll get started on this. It should be a quick fix.

**Comment by harshilsharma63** [comment]
@ThiefMaster this is fixed and released as part of [v2.5.1](https://github.com/standup-raven/standup-raven/releases/tag/v2.5.1). One caveat remains that the count in plugin icons remains the same whether the Raven icons is visible or not. Unfortunately, there is nothing that can be done (reliably) to fix this.

<img width="311" alt="Screenshot 2020-04-27 at 6 14 30 AM" src="https://user-images.githubusercontent.com/8211068/80324402-5dc15780-884e-11ea-9546-85792d1e3510.png">

**Comment by bbodenmiller** [comment]
@harshilsharma did you file a feature request or anything with MM to make this easier/more reliable?

**Comment by harshilsharma63** [comment]
@bbodenmiller had created a feature request ticket. at - https://github.com/mattermost/mattermost-server/issues/14179 , but no response as of yet.
