### ISSUE TITLE
BUG - Remove leftover debug code

### ISSUE THREAD

**Issue by ThiefMaster** [standup-raven/standup-raven#141]
https://github.com/standup-raven/standup-raven/blob/master/server/plugin.go#L172

This is quite annoying since it spams the headers for every request to the plugin's http endpoints to the log, using the INFO log level.

**Comment by harshilsharma63** [comment]
@ThiefMaster that's a valid point. On it.

**Comment by harshilsharma63** [comment]
This has been fixed and will be part of 2.3.0 release.

**Comment by harshilsharma63** [comment]
@ThiefMaster this has been fixed in the latest release - 2.3.0. Please update your plugin installation.
