### ISSUE TITLE
PROPOSAL - Modify the report layout

### ISSUE THREAD

**Issue by ajellman** [standup-raven/standup-raven#145]
When the report is configured "Type Aggregated" the contributions by user are separated by a very large icon using a lot of space.  This makes it harder to read the entire report as a coherent whole.

Suggested change:  Make the user icon smaller or just use a label to identify the user so the report reads more contiguously.
<img width="371" alt="Screen Shot 2020-03-26 at 8 36 57 AM" src="https://user-images.githubusercontent.com/56693456/77647708-49cbc280-6f3d-11ea-9e3d-2079bd6cc036.png">

**Comment by jatinjtg** [comment]
@ajellman This was a mattermost bug in v5.18.0 (see  [here](https://github.com/mattermost/mattermost-server/issues/13539)) and was resolved in Mattermost v5.19.0. I will suggest you to upgrade your mattemost version to v5.19.0 or above.

**Comment by harshilsharma63** [comment]
@ajellman see #134 .
