### ISSUE TITLE
BUG - Can't save standup raven config

### ISSUE THREAD

**Issue by fstani** [standup-raven/standup-raven#166]
**Summary**
Can't save standup raven config after plugin install

**Steps To Reproduce**
1. Install Plugin
2. Type `/standup config` on any channel
3. Set properties according to screenshot
4. Receive error
```
An error occurred while saving standup config.
Unauthorized
MiddlewareAuthenticate: , Unauthorized
```

**Expected behavior**
Config saves

**Observed Behavior**
What actually happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/4691601/84805327-73dfce80-afda-11ea-9633-47115f0b68ba.png)

**Environment**
-  Mattermost Gitlab version: 5.21
-  Server OS: Linux
-  App OS: Windows
-  Platform: Desktop app
-  Platform Version: 4.3.2
-  Plugin Version: mattermost-plugin-standup-raven-v2.5.1-linux-amd64.tar

**Comment by fstani** [comment]
Some other information from the console:

A POST to:
`plugins/standup-raven/config`

Returns the 401 with this response in the body:
```
Unauthorized
MiddlewareAuthenticate: , Unauthorized
```

Seems like the issue happens on the Windows App version only, I was able to perform the config in the browser version:

Seems related to:
https://github.com/standup-raven/standup-raven/issues/64

But, I was not able to resolve it in the app after trying this instructions:
> Hmm, that's strange. I tried on Mattermost desktop app Macbook Pro as well and it worked fine. Maybe you can try View > Clear Cache and Reload?

**Comment by fstani** [comment]
Here's what actually worked, had to Log Out and Log In again

**Comment by harshilsharma63** [comment]
@fstani HI, glad the issue. is resolved for you. Did you recently upgraded from an older version of Mattermost? The solution you mentioned fixed the same issue for many users when they upgraded from a specific version of Mattermost (cannot recall which version it was though).

**Comment by fstani** [comment]
No @harshilsharma, I don't think I have, although I might've tested the plug-in before in the past, I'm uncertain right now. Thanks for the reply.

It's a bit strange that it requires a logout and login to work, which is why it seemed that the issue was with the desktop app.

**Comment by harshilsharma63** [comment]
@fstani that's strange. Seems like an issue specific to Windows desktop app.

**Comment by fstani** [comment]
Perhaps, though some other colleagues also had similar issues using the plugin in their MacOS, I can ask tomorrow and see which setups had issues.

Also it's good to note that I've just installed the latest published version of the plugin, and it was the first time using it
