### ISSUE TITLE
BUG - Header button misbehaves

### ISSUE THREAD

**Issue by astralcar** [standup-raven/standup-raven#168]
**Summary**
Header button takes up whole channel in Firefox.

**Steps To Reproduce**
1. Open a channel with the raven enabled
2. The header button takes up the whole window and floats over the channel chat, covering it

**Expected behavior**
The button should be in its usual place in the header, with its appropriate size.

**Observed Behavior**
The button size follows the chat window size and covers up the channel. The button behaves properly only if the window is narrow enough to minimize the Mattermost side bar.

**Environment**
-  Mattermost version: 5.24.0
-  OS: Windows 10
-  Browser: Firefox 77.0.1

**Comment by harshilsharma63** [comment]
@astralcar thank you for the bug report. This is now fixed in [v2.5.2](https://github.com/standup-raven/standup-raven/releases/tag/v2.5.2).

**Comment by harshilsharma63** [comment]
Closing this now. Feel free to re-open in case you still face the issue.

Thanks 👍
