### ISSUE TITLE
BUG - Raven Icon enlarged & hides content

### ISSUE THREAD

**Issue by jprusch** [standup-raven/standup-raven#171]
**Summary**
After upgrade to MM 5.24 the Raven icon hides content & is shown enlarged on Firefox 77.0.1 

**Steps To Reproduce**
1. Open Firefox
2. Open Mattermost site with current version 5.25
3. Login & switch to channel with Standup Raven enabled

**Expected behavior**
A small raven icon is shown above the notification area,

**Observed Behavior**
The raven icon hides the notification content & is shown enlarged

**Screenshots**
![image](https://user-images.githubusercontent.com/9337414/85103286-a968ff80-b206-11ea-9d51-4ffc940c68dc.png)

**Environment**
-  Mattermost version: 5.25
-  OS: Linux Debian
-  Platform: Windows 10
-  Browser (if applicable): Firefox 77.0.1 only, Works with Chrome & Edge
-  Platform Version: 77.0.1

**Comment by jprusch** [comment]
All caches have been cleared.

**Comment by jprusch** [comment]
OK, fixed...

**Comment by harshilsharma63** [comment]
@jprusch thank you for the bug report. This is now fixed in [v2.5.2](https://github.com/standup-raven/standup-raven/releases/tag/v2.5.2).
