### ISSUE TITLE
BUG - v2.5.2 not working with Mattermost 5.25.0

### ISSUE THREAD

**Issue by praisebob** [standup-raven/standup-raven#181]
**Summary**
Newest plugin version v2.5.2 does not seem to be working with newest Mattermost 5.25.0

**Steps To Reproduce**
1. Install plugin via plugin upload feature in Mattermost System Console (mattermost-plugin-standup-raven-v2.5.2-linux-amd64.tar.gz)
2. Enable plugin in System Console.

**Expected behavior**
Standup Raven icon appears in GUI.

**Observed Behavior**
Standup Raven icon does not appear in GUI.

**Environment**
-  Mattermost version: 5.25.0
-  OS: CentOS Linux release 7.8.2003 
-  Platform: browser, desktop app (possibly all)
-  Browser (if applicable): any

**Comment by huzaifarif** [comment]
Plugin does not start properly. Getting these errors in the server logs:

`{"level":"error","ts":1595705384.6344297,"caller":"mlog/sugar.go:23","msg":"Couldn't marshal database schema version unexpected end of JSON input","plugin_id":"standup-raven"}
{"level":"error","ts":1595705384.6356332,"caller":"mlog/log.go:175","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"unexpected end of JSON input"}`

I tried looking around and found that `getCurrentSchemaVersion()` method doesn't check if the `key != nil` and proceeds to unmarshall the JSON and fails. After adding the `nil` check it fails again at fetching `workWeekStart` and `workWeekEnd` from the `oldConf` and fails parsing the possible `nil` value to integer.

**Comment by harshilsharma63** [comment]
@praisebob I tested with v5.25 and it's working perfectly. You won't see the Raven icon if standup is not enabled in a channel. It will show up as soon as you enable it from `/standup config`. Could this have been your issue?

**Comment by harshilsharma63** [comment]
@huzaifarif thanks a lot for the PR but the code you updated is going to be part of future v3.0.0 release but the issue being faced here is with v2.5.2.

**Comment by huzaifarif** [comment]
@harshilsharma63 oh my bad! thanks for pointing out.
But I still feel that those checks should be present as it would fail on new installations without those checks as I showed in the logs above. (Unless I'm doing something wrong here?)

May need to update PR to not be linked to this issue.

**Comment by praisebob** [comment]
> @praisebob sorry for the late reply.
> 
> I tested with v5.25 and it's working perfectly. You won't see the Raven icon if standup is not enabled in a channel. It will show up as soon as you enable it from `/standup config`. Could this have been your issue?

Hi, yes, thank you for that. v2.3.0 did not seem to require that. We wish to upgrade from v2.3.0 to v2.5.2 so I guess the expectation was that all settings form older version (including whether the plugin is enabled on particular channel) would transfer to the newer version. Will we have configure all the settings from the start for this new version? Or will `/standup config` will just enable the plugin while keeping the previous configuration? Upgrade instructions are pretty sparse and mentions only the need to backup database. Would appreciate any guidance on how to proceed with the upgrade preferably keeping current configuration. 

P.S. Apologies for raising alarm this way.

**Comment by harshilsharma63** [comment]
@praisebob all settings are persisted and you should be able to see the icon right away. In the worst case, a reload should bring it back up.

Apologies for the late reply.

**Comment by harshilsharma63** [comment]
@praisebob let me know if this still doesn't work for you.

**Comment by praisebob** [comment]
@harshilsharma63 Hello, yes. The icon reappeared after running `/standup config` in a particular channel and all settings remained as they were. Thank you very much, appreciate your help!
