### ISSUE TITLE
BUG - :emoji: not displayed in standup modal

### ISSUE THREAD

**Issue by absynth47215** [standup-raven/standup-raven#183]
**Summary**
Emoji entered with :emoji: syntax are not correctly displayed in the modal

**Steps To Reproduce**
1. Create a new standup 
2. Add an emoji to a question, our example: ":muscle: What did I achieve yesterday?"
3. Fill standup
4. See literally ".muscle: What did I achieve yesterday" in the modal [EDIT: I had to replace the first : with a . due to Github using the same emoji shortcode as Mattermost ;-)].

**Expected behavior**
I'd expect the modal to correctly parse and display emoji shortcode. 

**Observed Behavior**
Emoji were shown as ":emoji:"
 
**Screenshots**
![Bildschirmfoto 2020-07-22 um 08 31 42](https://user-images.githubusercontent.com/3737316/88142430-c887f200-cbf5-11ea-963f-c7cacbc91666.png)

**Environment**
- Mattermost: 5.24.2 E20 trial
- Standup Raven: 2.5.2

**Comment by harshilsharma63** [comment]
@absynth47215 apologies for the late reply. And thanks for the bug report.

Emoji support is a cool thing and not supporting is, well, not cool. I believe we never thought about emojis in section titles and so it never got implemented. A fix for this will also allow us to use markdown in there. 

This should be doable though as Mattermost provides a utility for exactly this task.function for rendering.

BTW would you be willing to work on this?

**Comment by absynth47215** [comment]
> BTW would you be willing to work on this?

Sorry, that's way out of my depth :) I am halfway fluent in PHP but that's about it. I'd love to look at the fix to understand how Mattermost does emoji replacement (I believe I found a similar issue at another point in my test setup) but I'm afraid that if I touched the code, you'd end up with more bugs, not less. :-)

**Comment by harshilsharma63** [comment]
No worries @absynth47215 !

**Comment by harshilsharma63** [comment]
@absynth47215 this will be released as part of v3.1.0.

We now have full markdown support in section titles so one can go nuts ✌️

Emoji example -

<img width="551" alt="Screenshot 2020-08-30 at 4 43 53 PM" src="https://user-images.githubusercontent.com/8211068/91657616-ffe49b00-eadf-11ea-921d-743714c26221.png">

You can even use images -

<img width="551" alt="Screenshot 2020-08-30 at 4 44 42 PM" src="https://user-images.githubusercontent.com/8211068/91657625-1b4fa600-eae0-11ea-9144-d267060bc4f9.png">
