### ISSUE TITLE
BUG - v3.0.0 introduce error "SqlChannelStore.Update: You can not modify an archived channel., "

### ISSUE THREAD

**Issue by mthld** [standup-raven/standup-raven#187]
**Summary**
When upgrading from v2.5.2 to v3.0.0 we get the following error:
```
2020-08-17T19:36:47.816+0200 error mlog/log.go:175 Unable to activate plugin {"plugin_id": "standup-raven", "error": "SqlChannelStore.Update: You can not modify an archived channel., "}
```

**Steps To Reproduce**
1. Download the v3.0.0 release from GitHub
2. Upload it to the admin console through the plugin management section
3. Accept the overwrite proposal
4. Get an error message saying the plugin cannot restart or being activated

**Expected behavior**
The plugin should be upgraded as expected without throwing this error.

**Observed Behavior**
The described error is shown in the logs.

Rolling back to v2.5.2 make the plugin work as expected.

**Environment**
-  Mattermost version: 5.25.0
-  Server OS: Debian GNU/Linux
-  Platform: browser
-  Browser (if applicable): Safari
-  Platform Version: 13.1.2

Thanks in advance for your help.

**Comment by harshilsharma63** [comment]
@mthld thanks a lot for the bug report ✌️! I'm successfully able to reproduce this bug. I'll work on this one.

**Comment by harshilsharma63** [comment]
@mthld this is now fixed in [v3.0.1](https://github.com/standup-raven/standup-raven/releases/tag/v3.0.1). Please try it out.

**Comment by mthld** [comment]
Hello @harshilsharma63,

Thanks for your work, however I know face the following error:
```
2020-08-24T20:39:17.329+0200 error mlog/log.go:190 Unable to activate plugin {"plugin_id": "standup-raven", "error": "Cannot upgrade Standup Raven from version 2.0.0 to 3.0.1. Please upgrade first to one of versions "}
```

Is it somewhat related to #191?

**Comment by harshilsharma63** [comment]
@mthld yes, that's the same as #191 . This will be fixed today.
