### ISSUE TITLE
BUG - Standup Raven addon dominates screen in Mattermost 5.25.3

### ISSUE THREAD

**Issue by TimIMC** [standup-raven/standup-raven#188]
Currently in my mattermost my standup raven icon addon dominates the screen.

Running 5.25.3 on Fedora 32 Linux with Firefox 79.0

On Chrome and on my Mac the addon icon is just a small icon in the top bar. In Firefox it dominates the whole screen. Have tried restarting mattermost and Firefox completely to fix to no avail.

My co-workers have also seen this in Firefox on Mac.

![image](https://user-images.githubusercontent.com/36947784/90459026-5ac2dd80-e143-11ea-8979-94a559826d04.png)

Screenshot best describes it. Anyone able to suggest a remedy?

Tim

**Comment by harshilsharma63** [comment]
Hi 👋 @TimIMC, this was fixed in [v2.5.2](https://github.com/standup-raven/standup-raven/releases/tag/v2.5.2). I recommend you to upgrade the plugin version.

Let me know if you still face the issue after upgrading.

**Comment by TimIMC** [comment]
We upgraded to v2.5.2 which does fix this problem.  Unfortunately it can't be seen on the Mac desktop app at all now.

**Comment by harshilsharma63** [comment]
@TimIMC I suppose you've upgraded from a version lower than v2.5.0. In v.2.5 we introduced a new feature that hides the Standup Raven button in channels where standup is not enabled. Is it possible you're looking in a such a channel? If not, it's probably a temporary WebSocket issue. Just try giving it a hard refresh (⌘ + Shift + R on Mac).

**Comment by TimIMC** [comment]
No sign in the channels it is supposed to be in (it shows up in browser)

Refreshing already tried (twice), deleting and re-adding the server via the preferences, and upgrading the desktop app to latest version

**Comment by harshilsharma63** [comment]
Hmm, that's weird, because I recreated your exact same config (Mattermost 5.25, Standup Raven 2.5, Mac Mattermost desktop app 4.5.2) and didn't face the issue.

Can you check the app console (`View` > `Developer Tools for Current Server`) and share any error you might be getting in there?

**Comment by TimIMC** [comment]
I just talked to my colleagues and they found that changing the address to the server from an alias to another helped.  It must have been blocking the alias.

**Comment by harshilsharma63** [comment]
@TimIMC glad it's resolved for you!
