### ISSUE TITLE
BUG - Bot allows same user to be added multiple times.

### ISSUE THREAD

**Issue by skyscooby** [standup-raven/standup-raven#19]
**Summary**
It is possible to successfully add User X twice to a standup configuration.. their answers are duplicated in the report.

**Steps To Reproduce**
Self explanatory.

**Expected behavior**
The bot should ignore requests to add the same user if already a member of the report.

**Observed Behavior**
User is listed multiple times in the /standupviewconfig

Members: userx, userx, usery, usery

**Environment (if applicable):**
Can be provided if necessary but isn't likely environment specific.

**Comment by harshilsharma** [comment]
Hi @skyscooby! I'm able to reproduce the bug locally.

Would you be willing to help fix the issue?
