### ISSUE TITLE
BUG - Upgrade from 3.0.0 to 3.0.1 fails

### ISSUE THREAD

**Issue by jprusch** [standup-raven/standup-raven#191]
**Summary**
An upgrade from 3.0.0 to 3.0.1 fails. Errors are logged.

**Steps To Reproduce**
1. Download release 3.0.1
2. Go to Plugins
3. Click on upload & select downloaded file for release 3.0.1
4. Upload the plugin
5. Overwrite existing version

**Expected behavior**
New plugin version is installed

**Observed Behavior**
Plugin cannot be updated. Errors are logged

**Log**
`2020-08-21T08:54:32.332+0200    error   mlog/log.go:190 Unable to install plugin. A plugin with the same ID is already installed.       {"path": "/api/v4/plugins", "request_id": "twpu63m9t7nqzqpkgoqqctq6mo", "ip_addr": "192.168.x.y", "user_id": "123456", "method": "POST", "err_where": "installExtractedPlugin", "http_code": 400, "err_details": ""}`
`2020-08-21T08:54:34.750+0200    dpanic  zap@v1.15.0/sugar.go:191        Ignored key without a value.    {"plugin_id": "standup-raven", "ignored": "Cannot upgrade Standup Raven from version 3.0.0 to 3.0.1. Please upgrade first to one of versions "}`
`2020-08-21T08:54:34.749+0200    error   mlog/sugar.go:23        Cannot upgrade Standup Raven from version 3.0.0 to 3.0.1. Please upgrade first to one of versions       {"plugin_id": "standup-raven"}`

**Environment**
-  Mattermost version: 5.26.0
-  OS: Debian Linux
-  Platform: Any
-  Browser (if applicable): Any

**Comment by harshilsharma63** [comment]
@jprusch I'm working on this one. Thanks for the bug repot!

**Comment by harshilsharma63** [comment]
I have started on this.

**Comment by harshilsharma63** [comment]
@jprusch  this has been fixed in [v3.0.2](https://github.com/standup-raven/standup-raven/releases/tag/v3.0.2). Feel free to re-open the issue if you still face the problem.
