### ISSUE TITLE
BUG - Plugin causes MM LHS Channel Menu to scroll

### ISSUE THREAD

**Issue by shieldsjared** [standup-raven/standup-raven#192]
**Summary**
When this plugin is enabled, it causes the new channel menu on the experimental sidebar to fail to render properly. Scrollbars appear. This issue was initially posted in [MM as a bug](https://github.com/mattermost/mattermost-server/issues/15322), and then after discovering it was related to this plugin, I closed it there and re-opened here.

**Steps To Reproduce**
1. Ensure the standup raven plugin is installed and enabled
2. Ensure the experimental sidebar is enabled (tested with 5.26)
3. Observe behavior in screenshots below

**Expected behavior**
Standup Raven plugin should not impact rendering of out of the box features.

**Observed Behavior**
Menu is forced to scroll.  Note that ths screenshot below was taken w/ plugin v.2.5.2. After upgrading to 3.0.0, the menu is almost completely invisible now.

**Screenshots**
![channel-options-menu-2020-08-21_12-26-15](https://user-images.githubusercontent.com/600643/90929728-4abb3000-e3c7-11ea-91fd-64af805293c5.gif)

**Environment**
-  Mattermost v5.26
-  OS: Win 10
-  Browser: Chrome (was not an issue in old edge)

**Comment by harshilsharma63** [comment]
@shieldsjared this has been fixed in [v3.0.2](https://github.com/standup-raven/standup-raven/releases/tag/v3.0.2). Feel free to re-open the issue if you still face the problem.

**Comment by shieldsjared** [comment]
Looks good! Thanks so much @harshilsharma!  FYSA - tried to send you a coffee the other day, but got an error that international transactions were not supported/enabled.  Thanks again for the great plugin :)

**Comment by harshilsharma63** [comment]
@shieldsjared thanks! Can you tell where did you get the error on? I may have to enable something for that.

**Comment by shieldsjared** [comment]
@harshilsharma63 

https://www.buymeacoffee.com/harshilsharma63

**Error Message**
```
This account isn't enabled to make cross border transactions. You can enable your account at https://dashboard.stripe.com/account/international
```

**Comment by harshilsharma63** [comment]
@shieldsjared it's an issue with Stripe. I've disabled it for now until its resolved. Until then maybe you can try out via PayPal?

Thank you for the support ✌️
