### ISSUE TITLE
BUG - Plugin cannot be started after upgrade to 3.1 

### ISSUE THREAD

**Issue by jprusch** [standup-raven/standup-raven#199]
** After upgrading to 3.1 the plugin cannot be started **

**Expected behavior**
Plugin gets started

**Observed Behavior**
Error message is shown in Mattermost GI system console

**Environment**
-  Mattermost version: 5.26.0
-  OS: Linux Debian
-  Platform:  Windows Desktop App 4.5.3
-  Previous plugin: 3.0.2 (Runs after downgrade from 3.1)

**Comment by harshilsharma63** [comment]
@jprusch yeah, my bad, Will be releasing a new build in an hour.

**Comment by harshilsharma63** [comment]
@jprusch This is resolved in [v3.1.1](https://github.com/standup-raven/standup-raven/releases/tag/v3.1.1).
