### ISSUE TITLE
PROPOSAL - Option to disable reminders

### ISSUE THREAD

**Issue by hubpav** [standup-raven/standup-raven#20]
Today, Raven bot has 2 reminders:

1. Message `Please start filling your standup!`
2. Message `... - a gentle reminder to fill your standup.`

It would be nice to add the configuration option to switch them off. It should be doable on a per-channel basis.

**Comment by harshilsharma** [comment]
HI @hubpav!

Any specific reason for disabling the reminders? I'm trying to understand the scenario.

Thanks!

**Comment by hubpav** [comment]
Hi @harshilsharma 

Actually, one of the reasons the teams implement standup bots is to eliminate noise on the channels through aggregated reports. On the other hand, we want to have standup report time as wide as possible (let's say from 9 pm till 9 am) and having `Please start filling your standup!` 12 hours prior to standup is not desired.

Hereby I would prefer a possibility to configure standup aggregation start and announcement message as two independent things also with the possibility to switch it off completely to cut down the message noise.

I have addressed the idea of this here: https://github.com/standup-raven/standup-raven/issues/9#issuecomment-491524921

Thank you.

**Comment by harshilsharma** [comment]
@hubpav  Agreed that some teams may or may not want some notifications. This also seems easy to implement. Would you be willing to contribute by implementing this?

**Comment by hubpav** [comment]
@harshilsharma I am not a Go developer and thus the work on this would be very inefficient. However, I can offer comprehensive testing and provide feedback from the real deployment.

**Comment by harshilsharma** [comment]
@hubpav no worries. We'll keep this issue updated with designs once we start on this.

**Comment by harshilsharma63** [comment]
@hubpav If I understand you correctly, you still want the window open and close time, just not the two reminders. The report at window close time would still be posted automatically, Did I get that right?

**Comment by hubpav** [comment]
@harshilsharma Yes, your understanding is correct. The reason (besides others) why we have the standup bot is the aggregated output so it helps to avoid the new message notification spam :)

The possibility to squelch reminders would make our mornings calm even more ;) Thanks!

**Comment by harshilsharma63** [comment]
@hubpav got it!
