### ISSUE TITLE
PROPOSAL - Delete CURRENT DAY report when regenerating CURRENT DAY report

### ISSUE THREAD

**Issue by shieldsjared** [standup-raven/standup-raven#200]
**Is your feature request related to a problem? Please describe.**
While we have a deadline set on our standup, many folks get caught up in the day and miss the deadline. We first tried re-emphasizing the importance of submitting it on-time, but eventually found that our reports got more participation when we told folks "Hey, if you miss the deadline, still go in and do it, then issue the slash command `/standup report public` to repost the report".  Our channel is now full of progressive reports for the same day.  This makes using MM search VERY full of posts, and hard to get to the one you're after (which may not even be a MM post).  It also makes it hard when you're simply scrolling through the channel to see past reports (our team uses a single channel dedicated to standup)

**Describe the solution you'd like**
It would be great if you're posting the report for TODAY, that it delete the prior report that was posted. Perhaps this can be an option in the standup configuration (as I can also see some teams not liking this).

**Describe alternatives you've considered**
Currently, I go in every now and then (as a channel admin) and cleanup posts by hand... but that can be tedious.

Thanks for considering this!

**Comment by harshilsharma63** [comment]
@shieldsjared that's a very valid scenario. I wonder how good this combined with #94 would be. Thoughts?

cc - @skyscooby

**Comment by shieldsjared** [comment]
@harshilsharma63 - Yeup! Definitely along the same lines! In fact, I’d probably say that #94 is most accurate, and explicit report generation should remain untouched. If you agree, we can close this one out :)

**Comment by skyscooby** [comment]
@harshilsharma63 Yup I agree seems like a very similar workflow issue.

While I am no Golang programmer I feel like adding this type of thing shouldn't be too difficult.. a good enough solution might just be to check if the scheduled report posting is enabled and then check if the user report submit time is after the scheduled time but less than the next day.. I guess it might require defining when the user considers the end of the day to be.. if so dump the users report into the channel as an addition..

**Comment by shieldsjared** [comment]
@skyscooby @harshilsharma63 - I'm going to close this issue since it overlaps quite significantly w/ #94 (which would solve the use case that made me submit this).
