### ISSUE TITLE
BUG - Upgrade from 3.0.X to 3.1.X fails

### ISSUE THREAD

**Issue by dutsky** [standup-raven/standup-raven#202]
**Summary**
Can't upgrade plugin from 3.0.X to 3.1.X, but upgrading from 3.0.0 to 3.0.2 works fine

**Steps To Reproduce**
1. Go to System Console
2. Click on Plugin Management
3. Press "Choose File" in Upload plugin menu
4. Select `mattermost-plugin-standup-raven-v3.1.1-linux-amd64.tar.gz` and press "Upload"
4. See error "Received invalid response from the server" without any logs

**Expected behavior**
Plugin must be updated

**Observed Behavior**
Error "Received invalid response from the server" appears

**Screenshots**
![Screenshot_2020-09-23 System Console - Mattermost](https://user-images.githubusercontent.com/5102635/93985015-8dd93c00-fd95-11ea-913e-a86aadc382f5.png)

**Environment**
-  Mattermost version: 5.22.3
-  OS: Ubuntu 
-  Platform: browser
-  Browser (if applicable): firefox
-  Platform Version: 80

**Comment by harshilsharma63** [comment]
@dutsky you should be seeing some error messages in Mattermost logs when you activate the plugin. Can you share those?

**Comment by dutsky** [comment]
what do you mean by "activate"? Logs when I disable/enable the plugin:
```
{"level":"info","ts":1601979941.2570634,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"}
{"level":"info","ts":1601979945.849472,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"}
```

When I press "upload" button nothing writes in the logs and UI shows an error: "Received invalid response from the server"

**Comment by harshilsharma63** [comment]
@dutsky to clarify, this is what happens on a successful upload -

1. Upload gets completed successfully
2. You  get this popup asking confirmation for replacing the existing plugin
<img width="480" alt="Screenshot 2020-10-07 at 4 38 08 AM" src="https://user-images.githubusercontent.com/8211068/95269385-e826d200-0856-11eb-87e5-84e865fa9c97.png">
3. The plugin gets upgraded and enabled.

I believe it's failing at step 1  for you? If yes that's some issue with the  Mattermost installation itself. You can try setting the Mattermost log level to  `DEBUG` to check what's going on when you upload the plugin.

**Comment by dutsky** [comment]
When I uploading "mattermost-plugin-standup-raven-v3.0.2-linux-amd64.tar.gz" I'm getting this popup confirmation("overwrite existing plugin"), but when I trying to upload "mattermost-plugin-standup-raven-v3.1.1-linux-amd64.tar.gz" i'm still getting error: "Received invalid response from the server."
Logs shows nothing even at DEBUG level and if it's server issue, why uploading 3.0.2 works fine? 🤔

**Comment by harshilsharma63** [comment]
@dutsky Starting v3.1.x, we only support Mattermost versions 5.25.0 and above. That's why it's giving you an error.

**Comment by dutsky** [comment]
We upgraded Mattermost installation to 5.27.0, but it didn't help.

**Comment by harshilsharma63** [comment]
Ah, I see you're facing this issue with 5.27 as well. Can you share the logs generated between the moment you upload the plugin and you get the error? You can share to me directly over email to avoid any privacy issue.

**Comment by harshilsharma63** [comment]
We can also hop on a quick call if that would be helpful.

**Comment by dutsky** [comment]
Nevermind, it was reverse proxy settings issue. Sorry for the inconvenience.
