### ISSUE TITLE
BUG - 

### ISSUE THREAD

**Issue by ashfaqn** [standup-raven/standup-raven#203]
**Summary**
Unable to configure standup in a new or existing channel

**Steps To Reproduce**
1. Uploaded mattermost-plugin-standup-raven-v3.1.1-linux-amd64.tar.gz via System Console in mattermost 
2. Enabled the standup-raven plugin
3. Go to a channel
4. Enter a custom slash command '/standup config'
5. See error

**Expected behavior**
Following this url https://github.com/standup-raven/standup-raven/blob/v3.1.1/docs/user_guide.md, I expect to configure a standup for my mattermost channel

**Observed Behavior**
When I run /standup config, I get "Invalid command: config" error. Although I am able to run /standup help command. It seems that config subcommand is not available 

**Screenshots**
![image](https://user-images.githubusercontent.com/13698649/94526733-02edbb00-0247-11eb-91cb-0f9ac7f797de.png)

**Environment**
-  Mattermost version: e.g. 5.27.0
-  OS: Ubuntu 18.04.5 LTS
-  Platform: browser, desktop app
-  Browser (if applicable): e.g. firefox, Microsoft Edge
-  Platform Version: 85.0.564.51 (Microsoft Edge)

**Comment by harshilsharma63** [comment]
Hi @ashfaqn have you tried refreshing the bwowser/app after upgrading the plugin?

Also, do you see any errors in Mattermost logs or the browser console?

**Comment by ashfaqn** [comment]
I had refreshed the browser and restarted mattermost as well but in vain. 
In mattermost.log file, I have found the following lines but not sure if those would be helpful:

{"level":"dpanic","ts":1601299600.3168046,"caller":"zap@v1.15.0/sugar.go:191","msg":"Ignored key without a value.","plugin_id":"standup-raven","ignored":"Couldn't parse integer in old config work week start, defaulting to using 1 (Monday)"}
{"level":"error","ts":1601299600.3167078,"caller":"mlog/sugar.go:23","msg":"Couldn't parse integer in old config work week start, defaulting to using 1 (Monday) strconv.Atoi: parsing \"\": invalid syntax","plugin_id":"standup-raven"}
{"level":"dpanic","ts":1601299600.3174493,"caller":"zap@v1.15.0/sugar.go:191","msg":"Ignored key without a value.","plugin_id":"standup-raven","ignored":"Couldn't parse integer in old config work week end, defaulting to using 5 (Friday)"}
{"level":"error","ts":1601299600.3173773,"caller":"mlog/sugar.go:23","msg":"Couldn't parse integer in old config work week end, defaulting to using 5 (Friday) strconv.Atoi: parsing \"\": invalid syntax","plugin_id":"standup-raven"}

**Comment by harshilsharma63** [comment]
@ashfaqn those logs are fine and not the cause of this error. I suspect it to be an issue with the webapp-based slash commands in Mattermost itself. I suppose the command `/standup` is also not working for you? It should open up a dialog.

**Comment by ashfaqn** [comment]
@harshilsharma63 yes when I run `/standup` I get 

> ` Command with a trigger of '/standup' not found`

Have I missed configuring anything?

**Comment by negbie** [comment]
We ran into kinda same issue. Browser cache was cleared. Dev console shows this:

Uncaught (in promise) TypeError: Cannot read property 'enableErrorReporting' of null
    at StandupRavenPlugin._callee$ (standup-raven_7f8cf1253f8dfbb2_bundle.js:52833)
    at c (/static/5.e1943b1620914a1863b7.js:42)
    at Generator._invoke (/static/5.e1943b1620914a1863b7.js:42)
    at Generator.forEach.e.<computed> [as next] (/static/5.e1943b1620914a1863b7.js:42)
    at step (standup-raven_7f8cf1253f8dfbb2_bundle.js:52805)
    at standup-raven_7f8cf1253f8dfbb2_bundle.js:52805

**Comment by harshilsharma63** [comment]
@negbie thanks for the error log. Will resolve that.

**Comment by harshilsharma63** [comment]
@ashfaqn hmm, I think we'll have to revert one change we did a while back when we moved certain slash commands from the server to the webapp. That will stabilise it back.

Are you able to run `/standup viewconfig` BTW?

**Comment by harshilsharma63** [comment]
@ashfaqn please try out the beta build - [v3.0.2](https://github.com/standup-raven/standup-raven/releases/tag/v3.2.0). It should resolve this issue.

**Comment by ashfaqn** [comment]
@harshilsharma63 I uploaded v3.2.0, afterwards when I ran **/standup config** and **/standup viewconfig** I got the following messages respectively

`Configure your standup in the open modal!`

`Standup not configured for this channel`

**Comment by harshilsharma63** [comment]
@ashfaqn for `/standup config` did the configuration dialog open up this time?

**Comment by harshilsharma63** [comment]
`Standup not configured for this channel` is correct for `/standup viewconfig` if there is no standup configured for current channel.

**Comment by ashfaqn** [comment]
> @ashfaqn for `/standup config` did the configuration dialog open up this time?

No, it didn't

**Comment by negbie** [comment]
@ashfaqn this is an open source project, so please stop to spam the maintainer! Just watch this issue patiently and try to help as good as you can!

**Comment by harshilsharma63** [comment]
@ashfaqn the v3.0.2 should have fixed it as we reverted the change which caused the bug. If after using the [v3.0.2](https://github.com/standup-raven/standup-raven/releases/tag/v3.2.0) and following basic steps such as a hard reload in your browser, logging out and logging in don't work, let's hop on a quick call and resolve this.

**Comment by harshilsharma63** [comment]
@negbie thanks there! It's fine though as I really would like to solve this 😄

**Comment by harshilsharma63** [comment]
@ashfaqn please feel free to ping me on hello at standupraven.com and we can have a call.

**Comment by christiansoe** [comment]
This seems to be unresolved. I am using mattermost 5.29.0 and latest plugin of 3.1.1.
I tried to open the console and it shows this error. still trying to figure out what causes this problem.

![image](https://user-images.githubusercontent.com/2566983/100202511-bec81f80-2f44-11eb-9199-8e1a8d9028d0.png)

**Comment by christiansoe** [comment]
I solved the problem. For the problem was that I didn't add :8065 to the site URL in the system console. I was using http://x.x.x.x
Changed it to http://x.x.x.x:8065
