### ISSUE TITLE
PROPOSAL - What happened to the schedule?

### ISSUE THREAD

**Issue by cadavre** [standup-raven/standup-raven#204]
**Is your feature request related to a problem? Please describe.**
No all stand-ups happens daily. It would be great to have a way to configure schedule for stand-ups.

**Describe the solution you'd like**
I like the solution that is documented in README:
<img width="1135" alt="config-schedule" src="https://user-images.githubusercontent.com/461796/95425574-c6a41400-0944-11eb-9443-c16577a9cd8d.png">

**Describe alternatives you've considered**
–

**Additional context**
What happened to schedule documented in README?

**Comment by harshilsharma63** [comment]
@cadavre the feature you mentioned in the screenshot is already implemented in Standup Raven v3 and above. Can you verify if you're on the right plugin version?

**Comment by harshilsharma63** [comment]
@cadavre Hi! I'm closing this ticket as the functionality is already implemented and released. Feel free to re-open if you're unable to see the new features.

Thanks!

**Comment by cadavre** [comment]
Hi, thanks for letting know! I installed plugin officially provided by Mattermost Plugin Store and there's version... 2.something. Updated with latest release from Github, ale there it is. Thanks and sorry for hassle. :)
