### ISSUE TITLE
PROPOSAL - add option to complete and publish standup publicly to channel immediately - one step

### ISSUE THREAD

**Issue by eyebank** [standup-raven/standup-raven#218]
**Is your feature request related to a problem? Please describe.**
it appears user needs to complete standup and then
post standup publicly

**Describe the solution you'd like**
One step process where user completes and can publish standup (publicly) in one step.

**Describe alternatives you've considered**
Step 1) issue command /standup
Step 2) complete standup
Step 3) issue command ) /standup report public

**Comment by harshilsharma63** [comment]
> it appears user needs to complete standup and then
post standup publicly

You need to do this only if the standup was submitted _after_ the standup window closed. Any standup submitted before the window end time is part of the automatic report. Is this what's happening in your case?

**Comment by eyebank** [comment]
Thank you @harshilsharma63. I didn't realize there was an automatic publish within the window. Regardless, I will train staff to use the two commands if outside the window.

Thanks for all you do on this project.

**Comment by harshilsharma63** [comment]
@eyebank Yes, you'll need t manually publish the report only if you want it before or after the window close time.

Glad it worked out!
