### ISSUE TITLE
PROPOSAL - Set multiple standup reminders attached to per user/member

### ISSUE THREAD

**Issue by eyebank** [standup-raven/standup-raven#219]
**Is your feature request related to a problem? Please describe.**
As i understand the schedule feature, there is only one schedule range and it is applied globally.  

**Describe the solution you'd like**
i would like more control to the schedule based on user/member. basically if a user starts at 4pm id like that user to fill in his stasndup within the 1st 15 minutes. the same for an 8 am start and midnight start.

**Describe alternatives you've considered**
creating a channel for each user. not practical.

**Additional context**

**Comment by harshilsharma63** [comment]
@eyebank thanks for the feature recommendation. Unfortunately, per-user level standup scheduling is out of the core idea and scope of this project.

I propose this alternate approach - set up standup range as 12:00 AM to 11:59 PM. That way, anyone can submit their standup whenever they want across the day and there will be one, aggregated report for the day at the end of the day.
