### ISSUE TITLE
PROPOSAL -  possibility to write next day standup

### ISSUE THREAD

**Issue by patrickcaspeco** [standup-raven/standup-raven#220]
**Is your feature request related to a problem? Please describe.**
Our team usually writes our stand ups in the early mornings. The last thing we do everyday is to plan tomorrow's tasks. 
I, for example, have to write them down in a notepad first and then copy it in to the Raven bot next morning.

**Describe the solution you'd like**
You could have a checkbox next to the the window time frame settings. When the checkbox is activated, nobody can enter standups after the window closes that day and the stand up reports for that day is "done".
If someone opens standup Raven after the window has closed you would be entering your standup for the next day.

**Describe alternatives you've considered**
On hack we considered was to change the timezone so the window would be at midnight in another country but in the morning for us. 😆 But we didn't do that.

**Comment by harshilsharma63** [comment]
@patrickcaspeco thanks for the feature request. This is the same solution we arrived for #16.

**Comment by patrickcaspeco** [comment]
Ah ok. Awesome :) 
I will close this one.
