### ISSUE TITLE
BUG - Plugin doesn't start after upgrade to 3.2.0

### ISSUE THREAD

**Issue by jprusch** [standup-raven/standup-raven#229]
**Steps To Reproduce**
1. Download latest 3.2.0 release for linux
2. Upgrade the plugin via system console -> plugins -> upload
3. Overwrite existing version
4. Error message: Plugin could not be started after upgrade

**Expected behavior**
Plugin is started

**Observed Behavior**
Logged message:
2020-11-30T10:29:34.184+0100    error   mlog/log.go:229 Unable to restart plugin on upgrade.    {"path": "/api/v4/plugins", "request_id": "5xxxxxxqac", "ip_addr": "1.1.1.1", "user_id": "mxxxxxxxy", "method": "POST", "err_where": "installExtractedPlugin", "http_code": 500, "err_details": "unable to start plugin: standup-raven: fork/exec plugins/standup-raven/server/plugin.exe: no such file or directory"}

**Environment**
-  Mattermost version: 5.29.0 Enterprise
-  OS: Linux 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
-  Platform: Windows Desktop Client 4.6.1

**Comment by eyebank** [comment]
I can confirm version 3.2.0 does not launch. 
We rolled back to 3.1.1.

**Comment by harshilsharma63** [comment]
@jprusch @eyebank this will be resolved today.

**Comment by harshilsharma63** [comment]
@jprusch @eyebank Re-download the plugin from GitHub release once again and run that. The new ones will work fine.

**Comment by harshilsharma63** [comment]
@jprusch @eyebank did you get a chance to try it?

**Comment by jprusch** [comment]
Thx, works! Great job!

**Comment by harshilsharma63** [comment]
@jprusch Awesome. It was a bug in plugin bundling logic which left out the server executables.
