### ISSUE TITLE
BUG - Issued Command "/standup report public [DATE]" does not post publicly

### ISSUE THREAD

**Issue by eyebank** [standup-raven/standup-raven#237]
System
09:35(Only visible to you)
Submit your standup from the open modal!

System
09:36(Only visible to you)
Standup reports generated

System
09:37(Only visible to you)
Configure your standup in the open modal!

System
09:38(Only visible to you)
Standup reports generated

System
09:40(Only visible to you)
Standup reports generated

**Comment by ayusht2810** [comment]
The issue was not reproducible on the latest minimum supported version. Closing the issue now
