### ISSUE TITLE
BUG - Icon missing in desktop app

### ISSUE THREAD

**Issue by the02** [standup-raven/standup-raven#238]
**Summary**
Configured Raven for a Channel. Opening this channel in any browser shows the raven icon in the top bar. In the desktop app there is space reserved, but no icon shown

Mattermost Version: 5.27.0
Database Schema Version: 5.27.0
Database: mysql

Desktop app version 4.6.1 on Arch

**Steps To Reproduce**

**Expected behavior**
What you expected to happen.

**Observed Behavior**
What actually happened.

**Screenshots**
desktop app
![Screenshot_20201219_144501](https://user-images.githubusercontent.com/44460811/102690900-ebe8b480-4208-11eb-9f2d-434a8d24a767.png)

chrome incognito mode
![Screenshot_20201219_144439](https://user-images.githubusercontent.com/44460811/102690903-ec814b00-4208-11eb-9ed6-b0000fcdaca9.png)

**Environment**
-  Mattermost version: e.g. 5.11
-  OS: e.g. iOS
-  Platform: browser, desktop app, mobile browser, mobile app
-  Browser (if applicable): e.g. firefox, chrome
-  Platform Version: e.g. 68

**Comment by harshilsharma63** [comment]
@the02 this is fixed in v3.2.1 released today. Please upgrade to the latest version. Feel free to re-open this issue if you still face the issue.

**Comment by the02** [comment]
confirmed, thanks for the quick fix
