### ISSUE TITLE
BUG - Standup Raven icon covers whole screen in Firefox 84

### ISSUE THREAD

**Issue by jprusch** [standup-raven/standup-raven#251]
**Steps To Reproduce**
1. Install Standup Raven 3.2.1 on MM 5.30.0
2. Enable Satndup Raven in a channel
2. Open MM with Firefox 84
3. Switch to channel with Standup Raven

**Expected behavior**
Standup Raven icon in top row is scaled like the other icons

**Observed Behavior**
Icon covers whole screen

**Screenshots**
<img width="1185" alt="raven321_firefox84" src="https://user-images.githubusercontent.com/9337414/103509457-7bc26b80-4e63-11eb-97b5-bf0d3b900d46.png">

**Environment**
-  Mattermost version: 5.30.0
- Standup Raven 3.2.1
-  OS: Windows
-  Platform: browser
-  Browser (if applicable): Firefox
-  Platform Version: 84

**Comment by eyebank** [comment]
+1 we have also experienced this behavior. 

Mattermost version: 5.29.0
Standup Raven 3.2.1
OS: Windows
Platform: browser
Browser (if applicable): Firefox
Platform Version: 84

resolution: 
disable raven plugin. this works inconsistently

We have had to remove the standup raven plugin until fix distributed.

**Comment by harshilsharma63** [comment]
@jprusch @eyebank this will be fixed in today's release.

**Comment by harshilsharma63** [comment]
@jprusch @eyebank please upgrade to [v3.2.2](https://github.com/standup-raven/standup-raven/releases/tag/v3.2.2). It's now resolved.

**Comment by jprusch** [comment]
Thanks, tested on Firefox. Fixed!
