### ISSUE TITLE
BUG - Unable to find the existing channel | This plugin failed to start. Check your system logs for errors

### ISSUE THREAD

**Issue by anwiev** [standup-raven/standup-raven#254]
**Summary**
I'm trying to update Standup-Raven to version 3.2.2 but I got the error "This plugin failed to start. Check your system logs for errors."  (with other versions higher than v2.5.2 the same problem)

**Screenshots**
![image](https://user-images.githubusercontent.com/50668058/104319274-5085ef00-54e9-11eb-98ba-04ff625c50a1.png)

**Log from the server:**

`{"level":"info","ts":1610454829.7219336,"caller":"bleveengine/bleve.go:267","msg":"UpdateConf Bleve"}
{"level":"error","ts":1610454829.8493688,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"GetChannel: Unable to find the existing channel., resource: Channel id: uom8ryofh3bo9gtwwhcmqxs5gw"}
{"level":"error","ts":1610454830.0284326,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"GetChannel: Unable to find the existing channel., resource: Channel id: uom8ryofh3bo9gtwwhcmqxs5gw"}
{"level":"error","ts":1610454830.2468505,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"GetChannel: Unable to find the existing channel., resource: Channel id: uom8ryofh3bo9gtwwhcmqxs5gw"}
{"level":"error","ts":1610454830.4646997,"caller":"mlog/log.go:229","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"GetChannel: Unable to find the existing channel., resource: Channel id: uom8ryofh3bo9gtwwhcmqxs5gw"}
`

**Environment**
-  Mattermost version: 5.30.0
-  OS: Ubuntu 18.04 
-  Platform: any

**Comment by harshilsharma63** [comment]
@anwiev which version of the plugin were you previously on?

**Comment by anwiev** [comment]
@harshilsharma63, v2.5.2

**Comment by anwiev** [comment]
Hi @harshilsharma63,  I was just wondering if there'd been any developments?

**Comment by harshilsharma63** [comment]
Hi @anwiev I didn't get a change to look deep into this but this occurs when one of the channel you had standup configured for was deleted.

Can you try upgrading incrementally?

If that doesn't work, just mail me at hello@standupraven.com and we'll hop on a quick call. I'll be glad to get this resolved for you.

**Comment by harshilsharma63** [comment]
@anwiev I believe you deleted one of the channels in which standup was configured?

**Comment by harshilsharma63** [comment]
@anwiev This will be fixed now. We'll skip channels which are not found.

**Comment by harshilsharma63** [comment]
@anwiev This is now fixed in [v3.2.3](https://github.com/standup-raven/standup-raven/releases/tag/v3.2.3). Do check it out.

**Comment by anwiev** [comment]
@harshilsharma63, thank you, will try! :upside_down_face:
