### ISSUE TITLE
BUG - Incorrect french sentence

### ISSUE THREAD

**Issue by serut** [standup-raven/standup-raven#262]
**Summary**
We use Standup Raven and every morning, there is the same french typo repeated (`Ajourd'hui` instead of `Aujourd'hui`) for each member daily standup. It would be like writing `Tday` instead of `Today`...

**Screenshots**
![image](https://user-images.githubusercontent.com/2767218/111757664-da608880-889b-11eb-9826-c34a387ecb33.png)

Where is stored such i18n translation ? I don't know where it is.

**Comment by ayusht2810** [comment]
The issue was not reproducible on the latest minimum supported version. Closing the issue now
