### ISSUE TITLE
BUG - exec format error

### ISSUE THREAD

**Issue by harshilsharma** [standup-raven/standup-raven#27]
Filing a bug on behalf of @dangtu1795

I'm runing version 5.11 run by docker-compose on ubuntu 16.04 .Here is the error I encountered:

{"level":"error","ts":1558197389.5647445,"caller":"mlog/log.go:172","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"unable to start plugin: standup-raven: fork/exec /mattermost/plugins/standup-raven/server/plugin.exe: exec format error","errorVerbose":"fork/exec /mattermost/plugins/standup-raven/server/plugin.exe: exec format error\nunable to start plugin: standup-raven\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:216\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:95\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:172\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:35\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:333\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:80\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:59\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:245\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:187\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:167\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162\ngithub.com/mattermost/mattermost-server/app.(*RateLimiter).RateLimitHandler.func1\n\t/go/src/github.com/mattermost/mattermost-server/app/ratelimit.go:107\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}

@harshilsharma please help me.
Additional information:

    go version go1.12.2 linux/amd64

**Comment by harshilsharma** [comment]
Hi @dangtu1795! Thanks for reporting the bug.

This error is caused when you upload the wrong plugin binary that doesn't correspond with the OS of you Mattermost instance. Please upload the correct binary corresponding to the OS version you are running Mattermost on. Notice that in case of `mattermost-docker`, Mattermost always runs in a Linux environment irrespective of your OS, as it's running inside a Alpine Linux container.

Let me know if that fixes your issue.

**Comment by dangtu1795** [comment]
@harshilsharma thanks you so much. i downloaded "mattermost-plugin-standup-raven-v1.2.0-linux-amd64.tar.gz
8.98 MB" then it worked really well.

**Comment by harshilsharma** [comment]
@dangtu1795 glad to hear that!

Thank you for using Standup Raven. Please let us know if you have any feedback, suggestion or even better if you want to get involved as a contributor!
