### ISSUE TITLE
Standup Raven with mattermost 7.0.1

### ISSUE THREAD

**Issue by santhoshsoma23** [standup-raven/standup-raven#291]
Hello !

when i was trying to configure the standup raven in mattermost 7.0.1 version unable to do that.

But when i was trying to verify the status of the plugin it is up and running.

Some one can you please help me on that.

Thanks in Advance,
Santhosh.

**Comment by abbas-mehdi-naqvi** [comment]
This error is arising due to missing sentry server DSN. Added more details with screenshot in the below tagged issue.
https://github.com/standup-raven/standup-raven/issues/310
