### ISSUE TITLE
PROPOSAL - Upgrade plugin dependencies relevant to a Mattermost Web app React 17 upgrade

### ISSUE THREAD

**Issue by nevyangelova** [standup-raven/standup-raven#295]
**Is your feature request related to a problem? Please describe.**
As we are moving towards using React 17 and later next year React 18, we would need to upgrade all of our used plugins so we make sure they don't break for our customers.

**Describe the solution you'd like**
Look into upgrading package dependencies for this plugin, and ideally upgrading it to using React 17 as well. Or at least the current versions should work correctly when loaded in the new version of Mattermost Web app. 

**Describe alternatives you've considered**
Alternatively we can disable this plugin for all users until we are ready to proceed with the upgrades.

**Additional context**
We have a [document](https://docs.google.com/document/d/1-qWIIH8JtxKo6sTxxzxBgTcLNa3YkhcjRd0D2MLPRoY/edit) detailing our plans and next steps regarding the React 17 upgrade in Mattermost Web app.

**Comment by ayusht2810** [comment]
Fixed in PR https://github.com/standup-raven/standup-raven/pull/317. Closing the issue.
