### ISSUE TITLE
[PROPOSAL] Implement Permission System for Configuring Standups

### ISSUE THREAD

**Issue by harshilsharma** [standup-raven/standup-raven#3]
**Is your feature request related to a problem? Please describe.**
Any member of a standup channel can update channel standup config. This may not be desirable for some organizations.

**Describe the solution you'd like**
Enterprise Mattermost installations allow granting the user a role of `system admin` or `channel admin`. We can use this existing permission feature to only allow `channel admins` to configure standards for a channel. The team lead can be made `channel admin` with others remain with the regular role of `channel members`.

**Comment by PareshSolankiMI** [comment]
Any update for this request?

**Comment by harshilsharma63** [comment]
@PareshSolankiMI this is the next item on my to-do list but it will be included only in August release. You can, however, use a custom build of the plugin once the feature is complete.

On a side note, would you be interested in helping on this feature?
