### ISSUE TITLE
add reactDOM to webapp dependencies as per MM pull 1489

### ISSUE THREAD

**Issue by nough** [standup-raven/standup-raven#301]
Recent Mattermost release has recommended that plugins add ReactDOM as an external dependency. Does this need to be done to this webapp?

https://docs.mattermost.com/upgrade/important-upgrade-notes.html
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1489

The fix would be to add `  'react-dom': 'ReactDOM', `to the externals section of webapp/webpack.config.js

**Comment by ayusht2810** [comment]
Fixed in PR https://github.com/standup-raven/standup-raven/pull/306. Closing the issue.
