### ISSUE TITLE
PROPOSAL - Make the Timezone be channel specific

### ISSUE THREAD

**Issue by attzonko** [standup-raven/standup-raven#31]
**Is your feature request related to a problem? Please describe.**
Today our instance of Mattermost is used across many different timezones. Having the stand up raven only have a single global timezone does not work well for all our different teams.

**Describe the solution you'd like**
It would be great if we can configure the timezone per channel, so the standup window would be channel/timezone specific.

**Describe alternatives you've considered**
Not sure what else can be done to fix this.

**Additional context**
N/A

**Comment by harshilsharma** [comment]
@attzonko that's a great idea! Would you be willing to contribute on this one?

**Comment by attzonko** [comment]
> @attzonko that's a great idea! Would you be willing to contribute on this one?

Sounds like fun, I'll need to dive into Go, will keep you posted...

**Comment by harshilsharma63** [comment]
@attzonko great!

**Comment by harshilsharma** [comment]
@attzonko hi, just checking in if you've made any progress on this or if you need some help.

**Comment by attzonko** [comment]
I have started the process of learning golang :)

If you have any pointers on setting up the dev environment for developing and testing plugins please share. 

Thanks!
Alex

On Jun 4, 2019, at 4:54 PM, Harshil Sharma <notifications@github.com> wrote:

@attzonko hi, just checking in if you've made any progress on this or if you need some help.

**Comment by harshilsharma63** [comment]
@attzonko The quickest way to setup Mattermost locally is via docker, following the instructions over [here](https://github.com/mattermost/mattermost-docker). Standup Raven setup instructions are available over [here ](https://github.com/standup-raven/standup-raven/blob/master/docs/getting_started.md).

**Comment by harshilsharma63** [comment]
Let me know if you need any assistance with the issue. I'll be more than glad to assist!
