### ISSUE TITLE
BUG - Themes not considered  by standup raven

### ISSUE THREAD

**Issue by attzonko** [standup-raven/standup-raven#32]
**Summary**
When a user has selected dark theme fr Mattermost, some of the standup raven text become unreadable. 

**Steps To Reproduce**
1. Change your mattermost display theme to one of the default dark ones.
2. run `/standupconfig`
4. See drop down text, or rather 'can't see'

**Expected behavior**
Easily see the text in the drop downs

**Observed Behavior**
Text is dark blending in with dark background

**Screenshots**
![image](https://user-images.githubusercontent.com/4975715/58277485-ae7f2500-7d4e-11e9-9d27-470f3446e535.png)

**Environment (if applicable):**
-  Using the Windows Desktop Application for Mattermost

**Comment by harshilsharma** [comment]
@attzonko thanks for the bug report!

Does it only happen in the desktop app? It looks perfect for me on Mozilla Firefox on MacOS 
![](https://i.imgur.com/0rtYXkN.png)

I'll try on other environments as well.

**Comment by attzonko** [comment]
No I just tried it in Chrome as well as Internet Explorer. Same result in both, not sure what setting is different because I agree yours looks fine 😃 

![image](https://user-images.githubusercontent.com/4975715/58353397-3fbfcb80-7e23-11e9-876c-43f414f02064.png)

**Comment by harshilsharma63** [comment]
@attzonko what version of Mattermost are you on?

**Comment by attzonko** [comment]
> @attzonko what version of Mattermost are you on?

I am on 5.11

**Comment by harshilsharma** [comment]
@attzonko I tested this again today and the bug is re-occurring for me now. I'm investigating into it.

**Comment by harshilsharma** [comment]
It appears that the text color is not depending on Mattermost theme ans is always `#333333`. I've filed a bug report in Mattermost for the same. You can view the bug report over at https://github.com/mattermost/mattermost-server/issues/11059 .

**Comment by harshilsharma63** [comment]
﻿A pull request for fixing this has been created in Mattermost Webapp - https://github.com/mattermost/mattermost-webapp/pull/2950

**Comment by harshilsharma63** [comment]
The Mattermost fix will be released in v5.14, scheduled to release in August 2019.
