### ISSUE TITLE
Use changelog generation tool

### ISSUE THREAD

**Issue by harshilsharma** [standup-raven/standup-raven#34]
Using a changelog generation tool will -
1. eliminate one mundane task.
1. make changelogs consistent and neat.
1. actually make having a changelog in the first place.

Requirements to be satisfied -
1. Enforce good issue practices - using and updating correct labels.
1. Can be incorporated as a CI task.
1. Ideally, should run on JavaScript or Golang to prevent extra system dependencies, but not a hard limitation.
1. Supports GitHub releases

https://github.com/github-changelog-generator/github-changelog-generator#usage looks interesting and simple enough.

**Comment by hanzei** [comment]
What about https://github.com/goreleaser/goreleaser?

**Comment by harshilsharma** [comment]
@hanzei thanks for the suggestion!

goreleaser seems like a full release and publication tool but we already use [ghr](https://github.com/tcnksm/ghr) for that from CircleCI. 

What I'm looking for is something that can generate just the changelog based on commits, issue, and milestone. This way we can continue using the existing tooling and insert the generated changelog into the GitHub release.

**Comment by hanzei** [comment]
Goreleaser _can_ publish releases, but you don't have to. It allows you to generate changelogs locally and copy them to GH. I use it for Matterpoll and it works just fine.

**Comment by harshilsharma** [comment]
Well, I'm really liking what GitHub Desktop has done with their changelogs over at https://desktop.github.com/release-notes/ . I'm trying to run their changelog script as an independent codebase.

**Comment by harshilsharma** [comment]
Really impressed with the looks and the minimalism of GitHub Desktop release notes, I created [what-the-commit](https://github.com/standup-raven/what-the-changelog), by extracting the changelog code from GitHub Desktop repository.
