### ISSUE TITLE
BUG - Config modal "Repeat" selector is broken

### ISSUE THREAD

**Issue by mickmister** [standup-raven/standup-raven#365]
**Summary**

In the "Schedule" tab of the standup config modal, when clicking the "Repeat" selector arrow, the select box does not open. I am able to reproduce this in the following scenarios:

- Installing the latest release from https://github.com/standup-raven/standup-raven/releases/tag/v3.3.1
- Running the program locally in development, importing the `react-rrule-generator` as usual
- Running the program locally, directly importing `build/index.js` from a local cloned copy of https://github.com/standup-raven/react-bootstrap-rrule-generator

Issue does not reproduce in the scenario:

- Running the program locally, directly importing `src/lib/index.js` from a local cloned copy of `react-bootstrap-rrule-generator`

Building the `react-bootstrap-rrule-generator` project results in no change to `build/index.js`, so it seems its contents are already be sync'd with the `src` folder. I'm thinking there is something in the build process that is making this issue happen.

I'm not sure what the core issue is, but the bug exists in the production build of the plugin. Any thoughts on the what could be the issue or fix for this?

---

**Screenshots**

Timezone selector works

<img width="400px" src="https://github.com/standup-raven/standup-raven/assets/6913320/1b988a11-a3b3-4f77-a257-bd67d772c208"/>

Repeat selector does not

<img width="400px" src="https://github.com/standup-raven/standup-raven/assets/6913320/122721aa-12fe-4526-a006-2d8ef8c1cff6"/>

**Environment**
-  Mattermost version: 8.0
-  OS: Mac M1
-  Platform: browser
-  Browser (if applicable): chrome

**Comment by mickmister** [comment]
We can probably just move that library `react-bootstrap-rrule-generator` into this repo if the library is having an issue with its builds. That would likely solve this ticket, and would make it easier to make changes later if that part of the plugin needs to be updated.

I'm not sure who maintains that library or this plugin but I think this would make maintaining the plugin easier to have that library's code in this repo.

**Comment by andr-ec** [comment]
Is there any workaround in the meantime? I'm also seeing the same thing in production and need to change the repeat from weekly to daily.

**Comment by maxwellpower** [comment]
> Is there any workaround in the meantime? I'm also seeing the same thing in production and need to change the repeat from weekly to daily.

This is easier done on the web client and requires some experience with dev tools.

Right-click on the element for repeat and inspect, there is a `<div>` above the `<button>`. If we update the div to add the open class, the dropdown will work, and monthly can be selected. The div then becomes in full:
`<div class="dropdown open btn-group btn-group-link">`.

**Comment by andr-ec** [comment]
Oh I didn't think of that, I just copied the request from the network tab and sent it from curl. That worked well enough
