### ISSUE TITLE
PROPOSAL - Generate a report on window end without waiting for everyone to submit standup information

### ISSUE THREAD

**Issue by tomepejo** [standup-raven/standup-raven#38]
**Is your feature request related to a problem? Please describe.**
When some of our co-workers is on a vacation, the report is waiting for them to submit standup info too. Then the report is not automatically generated which means someone else should trigger the report action manually.

**Describe the solution you'd like**
Set a flag (boolean) "Wait for everyone to participate" true/false, so the bot will wait or not for the report at window close accordingly.

**Comment by harshilsharma** [comment]
Hi @tomepejo! Thanks for the proposal.

When the window close time approaches, a report is sent containing standup of all members who had submitted their standups. This report also contains the names of members who didn't submit their standups.

Only in the scenario that no one has filled their standup, is a standup report not sent.

Are you experiencing something out of this?

**Comment by sandipagarwal** [comment]
@tomepejo - I have been using it. And, I see the report coming in at the end of the window. You can confirm if it's not working for you.
I do like the concept of the boolean flag there. I see pitfall here. This flag needs to be switched each time someone is on vacation or not, in the case we want the bot to wait for all the people to submit the standups. Moreover, this flag would most (more) of times be set to false, which is already the default implementation.
CC: @harshilsharma

**Comment by tomepejo** [comment]
@harshilsharma, @sandipagarwal you were right. The report was generated even though not all users participated.

Probably we thought that it is an issue because of the window config in hours. There is an offset of 3 hours of the config and the actual time. But this is probably an issue in our server (setup), so will check with our DevOps.

Thank you.
