### ISSUE TITLE
PROPOSAL - Have the `@` in the standup report for people who have not submitted.

### ISSUE THREAD

**Issue by sandipagarwal** [standup-raven/standup-raven#40]
**Is your feature request related to a problem? Please describe.**
In the standup report, the people who have not submitted the standups should have the `@` against their usernames/handles.

**Comment by harshilsharma** [comment]
Thanks, @sandipagarwal for the suggestion!

This makes sense as it will act as a further reminder for members who haven't submitted their standups even at the time of report generation.

**Comment by harshilsharma** [comment]
This has been merged into master. INcluding this in v1.3 milestone.
