### ISSUE TITLE
PROPOSAL - Standup config custom section should not have 'Task for' prepended.

### ISSUE THREAD

**Issue by sonam-singh** [standup-raven/standup-raven#47]
Different projects can have different sections like in case we mentioned 'blockers' as well in standups. it would look like - `Tasks for blockers`. We should let the whole section name to be custom.

**Comment by goku321** [comment]
Can I take this one up?

**Comment by harshilsharma63** [comment]
@goku321 sure, that would be awesome! Let me know if you need any help with this issue or setting up things in general.

**Comment by goku321** [comment]
Thanks @harshilsharma63 :) Glad to take this up.

**Comment by harshilsharma63** [comment]
@goku321 hey, just checking for any progress.

**Comment by goku321** [comment]
Hi @harshilsharma63 did not make any progress yet as I was busy with other work. Give me a couple of days and I will get back to you on this. Thanks for your patience.

**Comment by goku321** [comment]
@harshilsharma63 Do I need to make changes in the webapp as well?

**Comment by harshilsharma63** [comment]
@goku321 sorry I missed your first message.

Regarding your question, yes, we need tome change in webapp as well. The text `tasks for` appears in one place in webapp -
![](https://i.imgur.com/lrsxGZY.png)

**Comment by harshilsharma63** [comment]
There is one usage of `tasks for` that I'm curious on how you intent to deal with - https://github.com/standup-raven/standup-raven/blob/24650a74b382c52007684a671408a96264f0630b/server/standup/notification/notification.go#L486

So in type aggregated reports, if a member has no tasks for a specific section, we currently show the text -

    John Doe has no tasks for <section name>

I can't come up with something to use in place of "tasks for" which will suite all section titles. I'm also open to removing that line all together.

**Comment by goku321** [comment]
How about using `open items for` instead of `tasks for` ?

**Comment by harshilsharma63** [comment]
@goku321 yeah, `open items for` sounds nice! So we are removing `tasks from from all places and adding `open items for` just in the one place I mentioned above. Did I get you right?

**Comment by goku321** [comment]
@harshilsharma63 yes, that's correct. I'll make the changes and create a PR then :)

**Comment by harshilsharma63** [comment]
Awesome job @goku321 !
