### ISSUE TITLE
BUG - Bot Profile Images are not loading

### ISSUE THREAD

**Issue by Nisarg10** [standup-raven/standup-raven#55]
**Summary**
When automatic reminder messages, reports get posted profile images of the bot is not getting loaded.
 
**Expected behavior**
Profile images should load.

**Observed Behavior**
Profile images not loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/14795254/59485544-d7995e00-8e93-11e9-91b2-48156f9ebfdf.png)
![image](https://user-images.githubusercontent.com/14795254/59485666-48d91100-8e94-11e9-8bfb-15f5fe929bfa.png)

**Environment**
-  Mattermost version: 5.10.0
-  OS:  Windows 10 Pro 
-  Platform: browser, desktop app
-  Browser (if applicable): chrome

**Comment by harshilsharma63** [comment]
@Nisarg10 this is a but with Mattermost v5.10 as discussed in #12.

You'll need to disable image proxy under `System Console` > `Files` > `Storage` > `Enable Image Proxy`.

**Comment by harshilsharma63** [comment]
Let me know if you still face the issue.

**Comment by Nisarg10** [comment]
@harshilsharma63 Thank you. Disabling image proxy worked.
