### ISSUE TITLE
Cannot save standup config

### ISSUE THREAD

**Issue by Michelleji** [standup-raven/standup-raven#64]
Hi 
After I enabled the standup-raven plugin in our Mattermost, I tried to run the /standupconfig in a new channel I just created but failed. I got an error "An error occurred while saving standup config. Unauthorized". I have no idea about this issue, can anyone help take a look?

Mattermost: 5.12.0
Standup-varen: 1.3.0

**Comment by tgly307** [comment]
Same issue with 1.4.0 and MM5.12

**Comment by harshilsharma63** [comment]
@Michelleji Standup Raven 1.3 is incompatible with Mattermost 5.12. You need Standup Raven 1.4 for that.

**Comment by harshilsharma63** [comment]
@tgly307 as for the issue you mentioned, I debugged it down to Mattermost not setting the `MMCSRF` cookie. I suppose you upgraded from 5.11 to 5.12 while your session was still active. If that's correct, try logging out and logging back in. Our organization was facing the same issue and this did the trick.

I've also filed a bug in Mattermost about the same - https://github.com/mattermost/mattermost-server/issues/11408

**Comment by tgly307** [comment]
@harshilsharma63 yes, your suggestion is correct, it about seesion issue. I logged out and in, it works well.

**Comment by Michelleji** [comment]
> @Michelleji Standup Raven 1.3 is incompatible with Mattermost 5.12. You need Standup Raven 1.4 for that.

I installed 1.4 and logged out and in, I still have this problem when I was using MM client in MacPro. MM webpage works well.

**Comment by harshilsharma63** [comment]
@Michelleji Hmm, that's strange. I tried on Mattermost desktop app Macbook Pro as well and it worked fine. Maybe you can try `View` > `Clear Cache and Reload`?

**Comment by Michelleji** [comment]
@harshilsharma63 I can use it in mattermost App now, thx for your help :)

**Comment by harshilsharma63** [comment]
@Michelleji @tgly307 glad to help!

**Comment by harshilsharma63** [comment]
@Michelleji @tgly307 we're gathering consent of organizations who use Standup Raven, to include their names in our marketing website. Would you folks be open to include your organization's entry as well - https://forms.gle/RCWFwgoNs2uoYHYHA ?

Thanks a ton!
