### ISSUE TITLE
BUG - No placeholder value available for timezone field in system console

### ISSUE THREAD

**Issue by harshilsharma63** [standup-raven/standup-raven#88]
**Summary**
No placeholder value available for timezone field in system console.

**Steps To Reproduce**
1. Install Standup Raven
1. Navigate to Standup Raven configuration section in system console.
1. Notice the value displayed for `Time Zone` field.

**Expected behavior**
Time zone field should indicate that no value is currently saved if it is so.

**Observed Behavior**
Time zone field shows the first time zone as the selected value even when no value is actually saved. 

This may cause confusion for a system admin whether that value being displayed is selected or is just a placeholder. Having a dedicated placeholder will solve this issue.

**Comment by SezalAgrawal** [comment]
Can I take up this task?

**Comment by harshilsharma63** [comment]
@SezalAgrawal sure, absolutely!

**Comment by harshilsharma63** [comment]
Let me know if you need any assistance.

**Comment by SezalAgrawal** [comment]
@harshilsharma I am new to this plugin so I am not sure how do I run the plugin to see this bug. I followed the steps as stated in https://github.com/standup-raven/standup-raven/blob/master/docs/getting_started.md.

**Comment by harshilsharma63** [comment]
@SezalAgrawal so, were you able to get the plugin running? Do you have Mattermost server running locally as well?

**Comment by SezalAgrawal** [comment]
@harshilsharma, I did the following steps:
1. Forked and cloned mattermost-server, set it up, run make run-server. I am getting {"AndroidLatestVersion":"","AndroidMinVersion":"","DesktopLatestVersion":"","DesktopMinVersion":"","IosLatestVersion":"","IosMinVersion":"","status":"OK"} when run curl command.
2. Forked and cloned standup-raven, ran make dist
3. Extracted mattermost-plugin-standup-raven-vx.y.z-darwin-amd64.tar.gz and placed in 
mattermost/plugins/standup-raven
4. Restarted server
5. Browsed http://localhost:8065/plugins/standup-raven. It tells me plugin is disabled. I can't find config.json file where I can enable the plugin

Can you tell me which step I am missing?
I followed docs as stated in https://developers.mattermost.com/contribute/server/developer-setup/
Do I need to setup mattermost-webapp to access the plugin?

**Comment by harshilsharma63** [comment]
@SezalAgrawal you don't need to extract the plugin tar.gz. There's a [detailed guide on this](https://docs.mattermost.com/administration/plugins.html) over at Mattermost. I'll post quick steps here for reference.

1. Navigate to `System Console` > `Plugins (BETA)` > `Plugin management`.
1. If the `Choose File` button is disabled, make sure `PluginSettings` > `EnableUploads` is set to `true` in Mattermost `config.json`.
1. Click on `Choose File` and select one of the `tar.gz` generated by `make dist` corresponding to your platform.
1. Once uploaded, add configurations and enable the plugin.

**Comment by SezalAgrawal** [comment]
@harshilsharma, I setup the mattermost-ewebapp, created system-admin account, but Choose file button is disabled. Where can I find the config.json file?
<img width="1433" alt="Screenshot 2019-08-13 at 12 38 17 PM" src="https://user-images.githubusercontent.com/13785694/62921940-bb4c6b80-bdc7-11e9-90ba-4c95b96c8408.png">

**Comment by SezalAgrawal** [comment]
@harshilsharma63 I was able to setup standup-raven plugin and ran it successfully. Will work on the bug now.

**Comment by harshilsharma63** [comment]
@SezalAgrawal that's awesome!

**Comment by SezalAgrawal** [comment]
@harshilsharma63 I tried this approach: Added an option {"display_name": "Select a timezone", "value": "defaultTimezone"}, in timezones.json and add default="defaultTimezone" in plugin.json. The only thing is it would display "Select a timezone" in the options also. Is it okay?
![image](https://user-images.githubusercontent.com/13785694/63222309-cc301f00-c1c3-11e9-81a5-de0dd21f7710.png)

**Comment by harshilsharma63** [comment]
@SezalAgrawal I'm not sure how much of the plugin features have you explored, but let me share some surrounding functionalities. The timezone value in system console is only a default value. A user can configure standup time on per-channel basis when they configure the standup for a channel. When they configure a channel standup, the value from system console is used as the default selected value in config modal. This behavior effectively makes the system console setting optional.

Based on this behavior, I'd think a better `display_name` would be "None" or something equivalent.

As for the `value` attribute, I think an empty value `value: ""` would make more sense as it can be easily detected and handled in code if required.

And yes, that extra option is fine. Actually, it's cool because it now allows someone to unset the default value as well!

**Comment by harshilsharma63** [comment]
Congrats @SezalAgrawal on your first completed Standup Raven issue!
