### ISSUE TITLE
PROPOSAL - Use sub commands instead of multiple commands

### ISSUE THREAD

**Issue by hanzei** [standup-raven/standup-raven#9]
**Is your feature request related to a problem? Please describe.**
The list of slash commands gets long, when this plugin is enabled. It currently adds six slash commands. More may follow.

**Describe the solution you'd like**
I propose to move all commands under one commands called `/standup`. E.g. it would be `/standup config` instead of `/standupconfig`.

**Additional context**
Inspiration can be taken from the GitHub plugin. See https://github.com/mattermost/mattermost-plugin-github/blob/master/server/command.go#L15-L34

**Comment by harshilsharma** [comment]
@hanzei thanks for the suggestion!

The general issue I see with a single command is with quick accessibility of its syntax. One would have to run `/standup help` for example to fetch a command's syntax.

With multiple commands and if they all have a common prefix (`/standup` in this case), one can type `/standup` and have the list populated with their syntaxes right there - 

![](https://i.imgur.com/NCJhJpn.png)

Thoughts?

**Comment by hubpav** [comment]
@harshilsharma I would also prefer single command much more - I understand your point, but this is quite an aggressive strategy and if every plugin worked liked that, the list would be quite messy soon.

As other issue mentioned, it would be super-handy to have the ability to fill out the standup report using the slash command.

It is probably beyond the scope of the original issue raised here, but here is my proposal for the slash command behavior:

```
/standup (print help)
/standup private (generate standup report privately)
/standup public (generate standup report publicly)
/standup config (view configuration)
/standup config enable (enable standup on this channel)
/standup config disable (disable standup on this channel)
/standup config add @member (add user to standup duty)
/standup config remove @member (remove user from standup duty) 
/standup config open 22:00 (open standup aggregation at this time)
/standup config close 9:00 (close standup aggregation at this time)
/standup config announce disable (disable standup start announcement)
/standup config announce 8:00 (schedule standup start announcement)
/standup config reminder disable (disable standup reminder message)
/standup config reminder 8:50 (schedule standup reminder message)
/standup submit 1 <message> (submit a record for predefined category 1)
/standup submit 2 <message> (submit a record for predefined category 2)
/standup submit ...
/standup flush (clear all submitted data)
```

What do you think about this? Thanks!

**Comment by harshilsharma** [comment]
@hubpav thanks for the slash command proposals! Pretty detailed work there.

We understand the issue with the possibility of growing slash command list in the system. We're exploring other plugins including GitHub plugin, as @hanzei suggested, on their UX regarding this.

**Comment by hubpav** [comment]
@harshilsharma Great, thank you! I am already looking forward to seeing the outcome :)
